reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
  collapse_walkthrough: true
  poem: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  high_level_summary: true
  path_filters:
    - "!pnpm-lock.yaml"
    - "!**/dist/**"

chat:
  auto_reply: true
  art: false
