// API diagnostics use finite, reviewed vocabulary, never runtime messages,
// URLs, SQL, identifiers, or a pattern that could admit arbitrary strings.
export const API_OPERATIONS = {
  "http.request": "HTTP request",
  "websocket.handshake": "WebSocket handshake",
  background: "background operation",
  "realtime.publish": "realtime event publication",
  "realtime.verify": "read-model notification verification",
  "websocket.hydrate": "WebSocket interest hydration",
  "websocket.revalidate": "WebSocket interest revalidation",
  "websocket.persist": "WebSocket interest persistence",
  "websocket.authorize": "WebSocket interest authorization",
  "websocket.event": "WebSocket event preparation",
  "websocket.operation": "WebSocket interest operation",
  "session.revoke": "session revocation notification",
  "session.clear-interest": "session interest cleanup",
  "container.recipients": "container grant recipient lookup",
  "billing.maintenance": "billing maintenance",
  "billing.trial-expiry": "free-trial expiry",
  "billing.trial-backoff": "free-trial expiry backoff",
  "billing.purge": "organization purge",
  "billing.purge-finalize": "organization purge finalization",
  "billing.purge-invalidate": "organization purge invalidation",
  "billing.seat-sync": "Stripe seat synchronization",
  "blob.maintenance": "blob maintenance",
} as const;

export type ApiDiagnosticOperation = keyof typeof API_OPERATIONS;

export const API_ERROR_CODES = {
  ECONNREFUSED: "connection refused",
  ECONNRESET: "connection reset",
  ECONNABORTED: "connection aborted",
  ETIMEDOUT: "connection timed out",
  EPIPE: "broken pipe",
  ENOTFOUND: "host lookup failed",
  EAI_AGAIN: "temporary DNS failure",
  ENETUNREACH: "network unreachable",
  EHOSTUNREACH: "host unreachable",
  ENOSPC: "storage full",
  EACCES: "permission denied",
  EMFILE: "file descriptor limit reached",
  "08000": "database connection failure",
  "08001": "database connection could not be established",
  "08003": "database connection does not exist",
  "08006": "database connection failure",
  "23502": "database not-null violation",
  "23503": "database foreign-key violation",
  "23505": "database unique constraint violation",
  "23514": "database check constraint violation",
  "40001": "database serialization failure",
  "40P01": "database deadlock",
  "42501": "database permission denied",
  "42703": "database column missing",
  "42P01": "database table missing",
  "53300": "database connection limit reached",
  "57014": "database query cancelled",
  "57P01": "database shutting down",
  "57P02": "database crash shutdown",
  "57P03": "database not ready",
  SQLITE_BUSY: "database busy",
  SQLITE_BUSY_SNAPSHOT: "database snapshot contention",
  SQLITE_LOCKED: "database locked",
  SQLITE_CONSTRAINT: "database constraint violation",
  SQLITE_CONSTRAINT_UNIQUE: "database unique constraint violation",
  STREAM_EXPIRED: "database stream expired",
  TRANSACTION_TIMEOUT: "database transaction timed out",
  HRANA_CLOSED_ERROR: "database transport closed",
  HRANA_PROTO_ERROR: "database transport protocol failure",
  HRANA_WEBSOCKET_ERROR: "database WebSocket transport failure",
  SERVER_ERROR: "upstream server failure",
  AccessDenied: "object storage access denied",
  NoSuchBucket: "object storage bucket missing",
  NoSuchKey: "object storage object missing",
  SlowDown: "object storage throttled",
  rate_limit: "upstream rate limit reached",
  api_connection_error: "upstream API connection failure",
} as const;

export const API_ERROR_TYPES = new Set([
  "PostgresError",
  "DrizzleError",
  "DrizzleQueryError",
  "LibsqlError",
  "SQLiteError",
  "RedisError",
  "SocketClosedUnexpectedlyError",
  "SocketTimeoutError",
  "ClientClosedError",
  "ClientOfflineError",
  "ConnectionTimeoutError",
  "S3Error",
  "StripeError",
  "StripeAPIError",
  "StripeConnectionError",
  "StripeRateLimitError",
  "StripeAuthenticationError",
  "StripeInvalidRequestError",
  "HTTPException",
  "AbortError",
  "TimeoutError",
]);

export function isVocabularyKey<T extends object>(
  vocabulary: T,
  value: unknown,
): value is keyof T & string {
  return typeof value === "string" && Object.hasOwn(vocabulary, value);
}
