import type { NegativeControl } from "./protocolNegativeControls";

export const SYSTEM_DESTINATION_NEGATIVE_CONTROLS: readonly NegativeControl[] =
  [
    {
      id: "read-projection-authorizes-mutation",
      module: "formal/local-trust/ContainerAuthoring.tla",
      config: "formal/local-trust/ContainerAuthoring.cfg",
      constants: { CheckAuthorAccess: "FALSE" },
      expect: { kind: "invariant", name: "AcknowledgementsHaveAuthority" },
      why: "An API read projection must not let a read-only signer trust an echoed mutation (#2266).",
    },
    {
      id: "root-acknowledgment-skips-document-priming",
      module: "formal/local-trust/RootDocumentPriming.tla",
      config: "formal/local-trust/RootDocumentPriming.cfg",
      constants: { ReprimeAfterRemoteAcknowledgment: "FALSE" },
      expect: { kind: "invariant", name: "DeferredDocumentsAreScheduled" },
      why: "A document deferred during root verification must be scheduled after acknowledgement (#2266).",
    },
    {
      id: "root-acknowledgment-never-reprimes-document",
      module: "formal/local-trust/RootDocumentPriming.tla",
      config: "formal/local-trust/RootDocumentPriming.cfg",
      constants: { ReprimeAfterRemoteAcknowledgment: "FALSE" },
      expect: { kind: "liveness", name: "DocumentEventuallySyncs" },
      why: "A document pass deferred before root acknowledgment must be scheduled again even if no further edit occurs.",
    },
    {
      id: "system-slot-created-in-wrong-topology",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { RequireSystemTopology: "FALSE" },
      expect: { kind: "invariant", name: "OnlyValidSystemTopology" },
      why: "Only the organization metadata slot may be a root; all other slots require a direct root parent, even with a truncated proof (#2266).",
    },
    {
      id: "root-manifest-crosses-organization",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { RequireRootScope: "FALSE" },
      expect: { kind: "invariant", name: "RootWritesStayInOrganization" },
      why: "A signed foreign root cannot be relabeled by an unsigned projection (#2266).",
    },
    {
      id: "system-slot-crosses-organization",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { RequireSystemScope: "FALSE" },
      expect: { kind: "invariant", name: "SystemWritesStayInOrganization" },
      why: "A missing local root row cannot select another organization's same-slot system container (#2266).",
    },
    {
      id: "session-root-from-view",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { PreserveSessionAcknowledgment: "FALSE" },
      expect: { kind: "invariant", name: "OnlyServerRootsAcknowledged" },
      why: "Restoring or switching a local view cannot acknowledge a server root (#2266).",
    },
    {
      id: "shared-system-refused",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { RejectSharedSystem: "TRUE" },
      expect: { kind: "invariant", name: "SharedSystemRemainsUsable" },
      why: "Extra recipients must not make a signed system destination unusable (#2266).",
    },
    {
      id: "cached-destination-can-move",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { PreserveDestinationIdentity: "FALSE" },
      expect: { kind: "invariant", name: "CachedDestinationsNeverMove" },
      why: "Cached root and system roles require immutable signed parent identities (#2266).",
    },
    {
      id: "system-destination-trusts-listing",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { VerifyDestination: "FALSE" },
      expect: { kind: "invariant", name: "OnlySignedSlotReceivesSystemWrites" },
      why: "A forged unsigned slot must not redirect private system writes.",
    },
    {
      id: "root-destination-ignores-session",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { RequireSessionRoot: "FALSE" },
      expect: { kind: "invariant", name: "OnlyOwnRootReceivesLocalContent" },
      why: "A different signed root must not adopt the session pre-login content.",
    },
    {
      id: "root-destination-ignores-creator",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { RequireRootCreator: "FALSE" },
      expect: {
        kind: "invariant",
        name: "OnlyUserCreatedRootReceivesLocalContent",
      },
      why: "An acknowledged root another identity created must not adopt the session pre-login content (#2278 M2).",
    },
    {
      id: "login-swaps-acknowledged-root",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { RefuseRootSwap: "FALSE" },
      expect: { kind: "invariant", name: "OnlyServerRootsAcknowledged" },
      why: "A later unsigned login must not replace an acknowledged organization's root (#2278 M2).",
    },
    {
      id: "system-slot-created-by-writer",
      module: "formal/local-trust/SystemDestination.tla",
      config: "formal/local-trust/SystemDestination.cfg",
      constants: { RequireSystemAdministrator: "FALSE" },
      expect: { kind: "invariant", name: "OnlyAdministratorsCreateSlots" },
      why: "A root writer must not mint a system-slot decoy.",
    },
  ];
