import type { NegativeControl } from "./protocolNegativeControls";

export const HISTORY_NEGATIVE_CONTROLS: readonly NegativeControl[] = [
  {
    id: "principal-resume-trusts-unsealed-progress",
    module: "formal/container-keying/PrincipalHistoryResume.tla",
    config: "formal/container-keying/PrincipalHistoryResume.cfg",
    constants: { TrustUnsealed: "TRUE" },
    expect: { kind: "invariant", name: "NoInventedProgress" },
    why: "Untrusted serialized progress cannot stand in for locally checked history.",
  },
  {
    id: "principal-resume-ignores-local-binding",
    module: "formal/container-keying/PrincipalHistoryResume.tla",
    config: "formal/container-keying/PrincipalHistoryResume.cfg",
    constants: { IgnoreBinding: "TRUE" },
    expect: { kind: "invariant", name: "ProgressBinding" },
    why: "Saved progress must bind its local key, revision and verification inputs.",
  },
  {
    id: "principal-resume-forgets-authority",
    module: "formal/container-keying/PrincipalHistoryResume.tla",
    config: "formal/container-keying/PrincipalHistoryResume.cfg",
    constants: { ForgetAuthority: "TRUE" },
    expect: { kind: "invariant", name: "AuthorityProgress" },
    why: "Restarting must preserve external-authority continuity.",
  },
  {
    id: "principal-page-publishes-unchecked-progress",
    module: "formal/container-keying/PrincipalHistoryPages.tla",
    config: "formal/container-keying/PrincipalHistoryPages.cfg",
    constants: { PublishEarly: "TRUE" },
    expect: { kind: "invariant", name: "OnlyCheckedPagesAdvance" },
    why: "A rejected page must not advance locally verified history (#2448).",
  },
  {
    id: "principal-page-forgets-external-authority",
    module: "formal/container-keying/PrincipalHistoryPages.tla",
    config: "formal/container-keying/PrincipalHistoryPages.cfg",
    constants: { ForgetAuthority: "TRUE" },
    expect: { kind: "invariant", name: "AuthorityProgress" },
    why: "Uncited pages must preserve the last verified authority reference (#2448).",
  },
  {
    id: "principal-history-write-cap-blocks-revocation",
    module: "formal/container-keying/PrincipalHistory.tla",
    config: "formal/container-keying/PrincipalHistory.cfg",
    constants: { CapWrites: "TRUE" },
    expect: { kind: "invariant", name: "RevocationAvailable" },
    why: "An authorized principal revocation must advance beyond the former history ceiling (#2442).",
  },
  {
    id: "principal-history-cold-recovery-cap",
    module: "formal/container-keying/PrincipalHistory.tla",
    config: "formal/container-keying/PrincipalHistory.cfg",
    constants: { CapReads: "TRUE" },
    expect: { kind: "invariant", name: "RecoveryCanProgress" },
    why: "Cache loss must not strand a previously accepted principal history (#2442).",
  },
  {
    id: "manifest-history-cold-read-bound",
    module: "formal/container-keying/ManifestHistory.tla",
    config: "formal/container-keying/ManifestHistory.cfg",
    constants: { IterativeVerification: "FALSE" },
    expect: { kind: "invariant", name: "HonestReadsAvailable" },
    why: "A warm accepted history must remain readable after cache eviction.",
  },
  {
    id: "manifest-history-mutation-cap-blocks-revocation",
    module: "formal/container-keying/ManifestHistory.tla",
    config: "formal/container-keying/ManifestHistory.cfg",
    constants: { CapMutations: "TRUE" },
    expect: { kind: "invariant", name: "RevocationAvailable" },
    why: "Limiting accepted history length cannot refuse an otherwise authorized revocation.",
  },
];
