// Generated by openapi-typescript from the document sync OpenAPI projection; do not edit.

export type paths = {
    "/documents/{documentId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["documents.sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    "documents.sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    authorizingContainerPathRefs?: ({
                        containerId: string;
                        manifestHash: string;
                    } & {
                        [key: string]: unknown;
                    })[][];
                    containerRekeys?: ({
                        body: unknown;
                        containerManifestHistory?: ({
                            event: {
                                [key: string]: unknown;
                            };
                            manifest: {
                                [key: string]: unknown;
                            };
                            manifestHash: string;
                            state: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        })[];
                        destinationParentContainerPath?: ({
                            event: {
                                [key: string]: unknown;
                            };
                            manifest: {
                                [key: string]: unknown;
                            };
                            manifestHash: string;
                            state: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        })[];
                        event: {
                            [key: string]: unknown;
                        };
                        expectedManifestHash: string;
                        keyEpoch: {
                            [key: string]: unknown;
                        };
                        keyring: {
                            [key: string]: unknown;
                        } | null;
                        manifest: {
                            [key: string]: unknown;
                        };
                        parentContainerPath?: ({
                            event: {
                                [key: string]: unknown;
                            };
                            manifest: {
                                [key: string]: unknown;
                            };
                            manifestHash: string;
                            state: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        })[];
                        parentKekState?: {
                            [key: string]: unknown;
                        } | null;
                        predecessorBridge: {
                            [key: string]: unknown;
                        } | null;
                        previousContainerPath?: ({
                            event: {
                                [key: string]: unknown;
                            };
                            manifest: {
                                [key: string]: unknown;
                            };
                            manifestHash: string;
                            state: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        })[];
                        previousManifest?: ({
                            event: {
                                [key: string]: unknown;
                            };
                            manifest: {
                                [key: string]: unknown;
                            };
                            manifestHash: string;
                            state: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        }) | null;
                        principalPolicies: {
                            [key: string]: unknown;
                        }[];
                        userRecipientKeys?: {
                            [key: string]: unknown;
                        }[];
                        wraps: {
                            [key: string]: unknown;
                        }[];
                    } & {
                        [key: string]: unknown;
                    })[];
                    contentKeyBundle?: {
                        contentKeyEpoch: number;
                        linkSetManifestHash: string;
                        targetHash: string;
                        targets: ({
                            containerId: string;
                            containerKeyEpoch: number;
                            containerKeyEpochId: string;
                            containerManifestHash: string;
                            wrappedKey: string;
                            wrappingMetadata: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        })[];
                    } & {
                        [key: string]: unknown;
                    };
                    contentKeyEpoch: number;
                    expectedLinkSetManifestHash: string;
                    expectedTargetHash: string;
                    localVersionVector: string | null;
                    minLsn?: string;
                    outgoingUpdates: ({
                        /** @constant */
                        checkpointKind?: "rotate_baseline";
                        /** @constant */
                        checkpointPayloadKind?: "full_history_snapshot";
                        encryptedData: string;
                        id: string;
                        partialEndVersionVector: string;
                        partialStartVersionVector: string;
                        plaintextHash: string;
                        sourceVersionVector?: string;
                        writeHeader: {
                            [key: string]: unknown;
                        };
                    } & {
                        [key: string]: unknown;
                    })[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful JSON response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        acceptedOutgoingUpdateIds: string[];
                        commitLsn: string | null;
                        contentKeyBundle: {
                            contentKeyEpoch: number;
                            documentId: string;
                            linkSetManifestHash: string;
                            targetHash: string;
                            targets: ({
                                containerId: string;
                                containerKeyEpoch: number;
                                containerKeyEpochId: string;
                                containerManifestHash: string;
                                wrappedKey: string;
                                wrappingMetadata: {
                                    [key: string]: unknown;
                                };
                            } & {
                                [key: string]: unknown;
                            })[];
                        } & {
                            [key: string]: unknown;
                        };
                        contentKeyBundles: ({
                            contentKeyEpoch: number;
                            documentId: string;
                            linkSetManifestHash: string;
                            targetHash: string;
                            targets: ({
                                containerId: string;
                                containerKeyEpoch: number;
                                containerKeyEpochId: string;
                                containerManifestHash: string;
                                wrappedKey: string;
                                wrappingMetadata: {
                                    [key: string]: unknown;
                                };
                            } & {
                                [key: string]: unknown;
                            })[];
                        } & {
                            [key: string]: unknown;
                        })[];
                        documentId: string;
                        documentKekTargets: {
                            documentId: string;
                            documentKeyTargetHash: string;
                            linkedContainerKeyEpochIds: string[];
                            linkedContainerManifestHashes: string[];
                            linkSetManifestHash: string;
                            targets: {
                                [key: string]: unknown;
                            }[];
                        } & {
                            [key: string]: unknown;
                        };
                        updates: ({
                            accessEpoch: number;
                            authorFingerprint: string;
                            /** @constant */
                            checkpointKind?: "rotate_baseline";
                            /** @constant */
                            checkpointPayloadKind?: "full_history_snapshot";
                            createdAt: string;
                            documentId: string;
                            encryptedData: string;
                            id: string;
                            partialEndVersionVector: string;
                            partialStartVersionVector: string;
                            plaintextHash: string;
                            sourceVersionVector?: string;
                            writeHeader: {
                                [key: string]: unknown;
                            };
                        } & {
                            [key: string]: unknown;
                        })[];
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Response without a declared JSON body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response without a declared JSON body */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response without a declared JSON body */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response without a declared JSON body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failure JSON response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        code: "document_not_found";
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Failure JSON response */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        code: "document_sync_conflict" | "document_sync_state_stale" | "document_sync_update_id_conflict";
                        error: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Response without a declared JSON body */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Response without a declared JSON body */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
