import { expect, test } from "bun:test";
import { renderOpenApi } from "./openApi";

test("checked-in OpenAPI artifact matches generated bytes", async () => {
  const artifact = new URL("../../../../docs/openapi.json", import.meta.url);
  expect(await Bun.file(artifact).text()).toBe(renderOpenApi());
});
