import {
  bindBlobAttachmentOperation,
  detachBlobAttachmentOperation,
  listDocumentAttachmentsOperation,
} from "./attachments";
import {
  challengeOperation,
  destroySessionOperation,
  listSessionsOperation,
  logoutOperation,
  registerOperation,
  userIdentityOperation,
  verifyOperation,
  webSocketTicketOperation,
} from "./auth";
import {
  receiveRevenueCatWebhookOperation,
  receiveStripeWebhookOperation,
} from "./billingWebhooks";
import {
  getBlobBytesOperation,
  uploadMultipartBlobPartBytesOperation,
} from "./blobBytes";
import {
  createContainerOperation,
  createContainerWithMetadataDocumentOperation,
  deleteContainerOperation,
  moveContainerOperation,
  reciteContainerOperation,
  rekeyContainerOperation,
  revokeContainerOperation,
  shareContainerOperation,
} from "./containerMutations";
import {
  getContainerKekLogOperation,
  listContainerDocumentsOperation,
  listContainerParentLanesOperation,
} from "./containerReads";
import {
  getDocumentAttributionOperation,
  listDocumentAttributionRangesOperation,
} from "./documentAttribution";
import {
  createDocumentOperation,
  getDocumentPurgeProofOperation,
  linkDocumentOperation,
  purgeDocumentOperation,
  unlinkDocumentOperation,
} from "./documentMutations";
import { documentSyncOperation } from "./documentSync";
import { getHealthOperation } from "./health";
import {
  completeMultipartBlobStageOperation,
  getMultipartBlobStageOperation,
  initiateMultipartBlobStageOperation,
} from "./multipartBlobs";
import {
  claimNativeOrganizationSubscriptionOperation,
  getOrganizationBillingHistoryOperation,
  getOrganizationBillingManagementUrlOperation,
  getOrganizationBillingOperation,
  getOrganizationNativePurchaseEligibilityOperation,
  startOrganizationTrialOperation,
} from "./organizationBilling";
import {
  createOrganizationGroupOperation,
  createOrganizationOperation,
  deleteOrganizationGroupOperation,
  getOrganizationDataUsageOperation,
  getOrganizationReadModelOperation,
  listOrganizationGroupMembersOperation,
  updateOrganizationProfileOperation,
  updateOrganizationRosterEntryOperation,
} from "./organizations";
import {
  commitOrganizationGroupPolicyOperation,
  getPrincipalPolicyOperation,
  putPrincipalPolicyOperation,
} from "./principals";
import {
  cancelStripeSubscriptionOperation,
  createStripeCheckoutOperation,
  createStripeCheckoutSessionOperation,
  createStripePortalOperation,
  getStripeCheckoutOptionsOperation,
} from "./stripeCheckout";
import {
  getContainerWriterProjectionOperation,
  getDocumentWriterProjectionOperation,
} from "./writerProjections";

// Name each imported operation type instead of expanding every Zod schema in
// the emitted declaration; the exact readonly tuple and runtime order stay intact.
export const protocolOperations: readonly [
  typeof getHealthOperation,
  typeof challengeOperation,
  typeof destroySessionOperation,
  typeof listSessionsOperation,
  typeof logoutOperation,
  typeof registerOperation,
  typeof userIdentityOperation,
  typeof verifyOperation,
  typeof webSocketTicketOperation,
  typeof getBlobBytesOperation,
  typeof receiveRevenueCatWebhookOperation,
  typeof receiveStripeWebhookOperation,
  typeof bindBlobAttachmentOperation,
  typeof detachBlobAttachmentOperation,
  typeof initiateMultipartBlobStageOperation,
  typeof getMultipartBlobStageOperation,
  typeof completeMultipartBlobStageOperation,
  typeof uploadMultipartBlobPartBytesOperation,
  typeof listDocumentAttachmentsOperation,
  typeof getDocumentAttributionOperation,
  typeof listDocumentAttributionRangesOperation,
  typeof createDocumentOperation,
  typeof getDocumentPurgeProofOperation,
  typeof linkDocumentOperation,
  typeof purgeDocumentOperation,
  typeof unlinkDocumentOperation,
  typeof getContainerKekLogOperation,
  typeof listContainerDocumentsOperation,
  typeof listContainerParentLanesOperation,
  typeof createContainerOperation,
  typeof createContainerWithMetadataDocumentOperation,
  typeof deleteContainerOperation,
  typeof moveContainerOperation,
  typeof reciteContainerOperation,
  typeof rekeyContainerOperation,
  typeof revokeContainerOperation,
  typeof shareContainerOperation,
  typeof getContainerWriterProjectionOperation,
  typeof getDocumentWriterProjectionOperation,
  typeof createOrganizationOperation,
  typeof getOrganizationBillingOperation,
  typeof getOrganizationBillingHistoryOperation,
  typeof getOrganizationBillingManagementUrlOperation,
  typeof getOrganizationNativePurchaseEligibilityOperation,
  typeof claimNativeOrganizationSubscriptionOperation,
  typeof startOrganizationTrialOperation,
  typeof getStripeCheckoutOptionsOperation,
  typeof createStripeCheckoutOperation,
  typeof createStripeCheckoutSessionOperation,
  typeof createStripePortalOperation,
  typeof cancelStripeSubscriptionOperation,
  typeof getOrganizationDataUsageOperation,
  typeof getOrganizationReadModelOperation,
  typeof createOrganizationGroupOperation,
  typeof deleteOrganizationGroupOperation,
  typeof listOrganizationGroupMembersOperation,
  typeof updateOrganizationProfileOperation,
  typeof updateOrganizationRosterEntryOperation,
  typeof getPrincipalPolicyOperation,
  typeof commitOrganizationGroupPolicyOperation,
  typeof putPrincipalPolicyOperation,
  typeof documentSyncOperation,
] = [
  getHealthOperation,
  challengeOperation,
  destroySessionOperation,
  listSessionsOperation,
  logoutOperation,
  registerOperation,
  userIdentityOperation,
  verifyOperation,
  webSocketTicketOperation,
  getBlobBytesOperation,
  receiveRevenueCatWebhookOperation,
  receiveStripeWebhookOperation,
  bindBlobAttachmentOperation,
  detachBlobAttachmentOperation,
  initiateMultipartBlobStageOperation,
  getMultipartBlobStageOperation,
  completeMultipartBlobStageOperation,
  uploadMultipartBlobPartBytesOperation,
  listDocumentAttachmentsOperation,
  getDocumentAttributionOperation,
  listDocumentAttributionRangesOperation,
  createDocumentOperation,
  getDocumentPurgeProofOperation,
  linkDocumentOperation,
  purgeDocumentOperation,
  unlinkDocumentOperation,
  getContainerKekLogOperation,
  listContainerDocumentsOperation,
  listContainerParentLanesOperation,
  createContainerOperation,
  createContainerWithMetadataDocumentOperation,
  deleteContainerOperation,
  moveContainerOperation,
  reciteContainerOperation,
  rekeyContainerOperation,
  revokeContainerOperation,
  shareContainerOperation,
  getContainerWriterProjectionOperation,
  getDocumentWriterProjectionOperation,
  createOrganizationOperation,
  getOrganizationBillingOperation,
  getOrganizationBillingHistoryOperation,
  getOrganizationBillingManagementUrlOperation,
  getOrganizationNativePurchaseEligibilityOperation,
  claimNativeOrganizationSubscriptionOperation,
  startOrganizationTrialOperation,
  getStripeCheckoutOptionsOperation,
  createStripeCheckoutOperation,
  createStripeCheckoutSessionOperation,
  createStripePortalOperation,
  cancelStripeSubscriptionOperation,
  getOrganizationDataUsageOperation,
  getOrganizationReadModelOperation,
  createOrganizationGroupOperation,
  deleteOrganizationGroupOperation,
  listOrganizationGroupMembersOperation,
  updateOrganizationProfileOperation,
  updateOrganizationRosterEntryOperation,
  getPrincipalPolicyOperation,
  commitOrganizationGroupPolicyOperation,
  putPrincipalPolicyOperation,
  documentSyncOperation,
];
