import openapiTS, { astToString } from "openapi-typescript";
import { renderOpenApi } from "../src/operation/openApi";

interface GeneratedArtifact {
  readonly expected: string;
  readonly file: URL;
  readonly label: string;
}

const openApiArtifact = new URL("../../../docs/openapi.json", import.meta.url);
const typeArtifact = new URL(
  "../src/operation/generatedOpenApi.ts",
  import.meta.url,
);
const openApiSource = renderOpenApi();
const arguments_ = process.argv.slice(2);

if (
  arguments_.length > 1 ||
  (arguments_.length === 1 && arguments_[0] !== "--check")
) {
  throw new Error("Usage: bun scripts/generateOpenApi.ts [--check]");
}

const generatedTypeAst = await openapiTS(openApiSource, {
  alphabetize: true,
  exportType: true,
  silent: true,
});
const generatedTypeSource = [
  "// Generated by openapi-typescript from the Tearleads OpenAPI projection; do not edit.",
  "",
  astToString(generatedTypeAst),
].join("\n");
const artifacts: readonly GeneratedArtifact[] = [
  {
    expected: openApiSource,
    file: openApiArtifact,
    label: "docs/openapi.json",
  },
  {
    expected: generatedTypeSource,
    file: typeArtifact,
    label: "packages/validators/src/operation/generatedOpenApi.ts",
  },
];

if (arguments_[0] === "--check") {
  const staleArtifacts: string[] = [];
  for (const artifact of artifacts) {
    const file = Bun.file(artifact.file);
    const actual = (await file.exists()) ? await file.text() : undefined;
    if (actual !== artifact.expected) {
      staleArtifacts.push(artifact.label);
    }
  }

  if (staleArtifacts.length > 0) {
    console.error(
      `${staleArtifacts.join(", ")} stale; run \`bun run generate:openapi\` and commit the result.`,
    );
    process.exitCode = 1;
  }
} else {
  for (const artifact of artifacts) {
    await Bun.write(artifact.file, artifact.expected);
    console.log(`Generated ${artifact.label}`);
  }
}
