export type {
  AddOrganizationGroupUserInput,
  BlobInfo,
  BlobInfoAttachmentKind,
  BlobInfoDocumentReference,
  BlobInfoInput,
  BlobInfoList,
  BlobInfoSort,
  BlobInfoSortDirection,
  BlobInfoSortKey,
  BrowserLocalKeyringOptions,
  ClientDatabaseOptions,
  ContainerContents,
  ContainerContentsContextValue,
  ContainerContentsStore,
  ContainerContentsStoreOptions,
  ContainerDocumentLinkInput,
  ContainerDocumentLinks,
  ContainerDocumentObjectSyncState,
  ContainerDocumentObjectSyncStatus,
  ContainerDocumentQueries,
  ContainerDocumentSidebarRow,
  ContainerInfo,
  ContainerInfoInput,
  ContainerItemRow,
  ContainerItemSort,
  ContainerItemSortDirection,
  ContainerItemSortKey,
  ContainerNode,
  ContainerShareAccessLevel,
  CreateOrganizationOptions,
  DatabaseListener,
  DatabaseOptions,
  DatabaseSnapshot,
  DatabaseStatus,
  DeviceFirst,
  DeviceFirstContainerContents,
  DocumentAttachmentStatus,
  DocumentAttachmentUpload,
  DocumentAttributionRangesInput,
  DocumentAttributionRangesPage,
  DocumentContextValue,
  DocumentInfo,
  DocumentInfoInput,
  DocumentList,
  DocumentSort,
  DocumentSortDirection,
  DocumentSortKey,
  DocumentStore,
  DocumentSubscriptionOptions,
  Documents,
  DocumentsRuntime,
  DomainScope,
  FileSaver,
  Identity,
  IdentityGenerationResult,
  IdentityKeyPackage,
  IdentityListener,
  IdentityOptions,
  IdentitySnapshot,
  ImportedOrganizationUser,
  IndexedDbLocalKeyringManifestStoreOptions,
  IndexedDbWrappingKeyKeystoreOptions,
  LinkDocumentToContainerInput,
  ListDocumentsInput,
  LocalKeyPurpose,
  LocalKeyring,
  LocalKeyringManifest,
  LocalKeyringManifestFormat,
  LocalKeyringManifestStorage,
  LocalKeyringManifestStore,
  LocalKeyringOptions,
  LocalKeyringPinCode,
  LocalKeyringScope,
  LocalKeyringSession,
  LocalOrganizationSummary,
  LocalProjectionReconciledDelta,
  LocalProjectionSnapshot,
  LocalProjectionView,
  LocalSecretContext,
  LocalStorageLocalKeyringManifestStoreOptions,
  Logger,
  MergeDocumentSummary,
  MoveDocumentToContainerInput,
  NetworkListener,
  NetworkMode,
  NetworkStatusSource,
  NormalizedLocalKeyringScope,
  OpenContainerDocumentInput,
  OpenDocumentInput,
  OpenDocumentOptions,
  OrganizationBilling,
  OrganizationBillingHistory,
  OrganizationBillingHistoryEntry,
  OrganizationBillingManagementUrl,
  OrganizationBillingView,
  OrganizationContainerGrant,
  OrganizationContainerGrants,
  OrganizationDataUsage,
  OrganizationDirectory,
  OrganizationDirectoryAndGroups,
  OrganizationDirectoryUser,
  OrganizationGrantRef,
  OrganizationGroupContainer,
  OrganizationGroupContainers,
  OrganizationGroupDetails,
  OrganizationGroupMember,
  OrganizationGroupMembers,
  OrganizationGroupPolicyHistory,
  OrganizationGroupSummary,
  OrganizationPolicyHistory,
  OrganizationProfile,
  Organizations,
  OrganizationUserDetail,
  PendingWriteQueueItem,
  PendingWriteQueueItemStatus,
  PendingWriteQueueObjectKind,
  PendingWriteQueueOperation,
  PendingWriteQueueOperationKind,
  PendingWriteQueueOperationStatus,
  PersistedDocumentListener,
  PinCodeBrowserLocalKeyringOptions,
  PinCodeWrappingKeyKeystoreOptions,
  PurgeDocumentInput,
  PurgeDocumentResult,
  ReconciliationService,
  RemoveOrganizationGroupUserInput,
  ResolvedUserIdentity,
  SaveFileRequest,
  SecurityIncident,
  SecurityIncidentListener,
  SecurityIncidentObjectKind,
  SecurityIncidents,
  Session,
  SessionContext,
  SessionCreateOrganizationResult,
  SessionListener,
  SessionRegistrationResult,
  SessionSnapshot,
  SetActiveDocumentContainerInput,
  SetLinkedContainerIdsForDocument,
  UnlinkDocumentFromContainerInput,
  UnwrapLocalSecretInput,
  UserIdentities,
  UserSession,
  WrapLocalSecretInput,
  WrappedLocalSecretEnvelope,
  WrappedLocalSecretFormat,
  WrappingKeyHandle,
  WrappingKeyKeystore,
  WrappingKeyMaterialStorage,
} from "./client";
export {
  type BlobStoreFactory,
  Blobs,
  type ClientOptions,
  createBrowserLocalKeyring,
  createBrowserLocalKeyringManifestStore,
  createBrowserNetworkStatusSource,
  createContainerDocumentObjectSyncState,
  createDomainScope,
  createIndexedDbLocalKeyringManifestStore,
  createIndexedDbWrappingKeyKeystore,
  createLocalKeyring,
  createLocalStorageLocalKeyringManifestStore,
  createMemoryLocalKeyringManifestStore,
  createMemoryWrappingKeyKeystore,
  createPinCodeBrowserLocalKeyring,
  createPinCodeWrappingKeyKeystore,
  createRevenueCatPurchases,
  createUnavailableDirectCheckout,
  createUnavailablePurchases,
  createWebViewLocalKeyring,
  Database,
  DEFAULT_DOCUMENT_ID,
  type DirectCheckoutAppearance,
  type DirectCheckoutCapability,
  type DirectCheckoutConfirmation,
  type DirectCheckoutSession,
  DirectCheckoutUnavailableError,
  decodeLocalKeyringSqliteKey,
  Events,
  type EventsListener,
  type EventsSnapshot,
  encodeLocalKeyringSqliteKey,
  enqueueReconciliationForEvents,
  IDENTITY_KEY_PACKAGE_FORMAT,
  isPinCodeWrappedLocalSecretEnvelope,
  LOCAL_KEYRING_MANIFEST_FORMAT,
  localKeyringScopeKey,
  Network,
  normalizeLocalKeyringScope,
  PurchaseAbortedError,
  PurchaseAlreadyOwnedError,
  PurchaseCancelledError,
  PurchaseIdentityPendingError,
  PurchaseProviderStalledError,
  type PurchasesCapability,
  PurchasesUnavailableError,
  parseLocalKeyringManifest,
  type RevenueCatBackend,
  type RevenueCatCustomerInfo,
  type RevenueCatPackage,
  type RevenueCatPurchasesConfig,
  SymCrypt,
  SyncBillingGate,
  type SyncBillingGateListener,
  type SyncPurchaseResult,
  type SyncSubscriptionOption,
  serializeLocalKeyringManifest,
  WRAPPED_LOCAL_SECRET_FORMAT,
} from "./client";
export type {
  BlobByteSource,
  BlobByteSourceInput,
  BlobBytes,
  BlobStore,
  DiscoveredDocumentInput,
  DocumentAttachment,
  DocumentClientProjectionDefinition,
  DocumentClientProjectionDeleteInput,
  DocumentClientProjectionSaveInput,
  DocumentFieldValidationIssue,
  DocumentProjection,
  DocumentProjectorDefinition,
  DocumentProjectorInput,
  DocumentProjectorRegistry,
  DocumentProjectorRegistryInput,
  DocumentRow,
  DocumentRowSummary,
  DocumentSummary,
  StoredDocumentKind,
  StoredDocumentState,
  StructuredDocumentMap,
  StructuredDocumentShape,
  StructuredDocumentText,
  ValidatedDocumentFields,
} from "./documents";
export {
  addDocumentAttachments,
  blobByteSourceInputLength,
  createBlobByteSource,
  createDocumentProjectorRegistry,
  createDocumentSignerDeviceId,
  DEFAULT_DOCUMENT_ACCESS_EPOCH,
  DEFAULT_DOCUMENT_KIND,
  defaultDocumentProjectorRegistry,
  deriveStoredDocumentTitle,
  ensureDocumentAttachmentStructure,
  getDocumentAttachments,
  getDocumentClientProjectionTables,
  getStoredDocumentTypeLabel,
  getUntitledDocumentTitle,
  initializeStoredDocumentKind,
  projectStoredDocumentState,
  readBlobByteSource,
  readStoredDocumentState,
  readStringDocumentField,
  resolveOpIdAttribution,
  sameDocumentAttachments,
  summarizeDocumentContributors,
  writerByPeerId,
  writeStoredDocumentFields,
} from "./documents";
export type {
  ContainerContentsSnapshot,
  ContainerContentsStoreRuntime,
  ContainerContentsStoreState,
  ContainerContentsStoreSyncAgent,
  ContainerContentsStoreSyncState,
  ContainerState,
  PurgeOptions,
  PurgeProgress,
} from "./stores/container-contents";
export {
  createContainerContentsStore,
  createContainerContentsStoreState,
  createContainerContentsStoreSyncAgent,
  getOrCreateContainerContentsStore,
  isSystemContainerNode,
  requestContainerContentsDocumentPriming,
  subscribeToContainerContentsStore,
  updateContainerContentsSnapshot,
  updateContainerContentsStoreRuntime,
} from "./stores/container-contents";
export type {
  DocumentSnapshot,
  DocumentStoreFacade,
  DocumentStoreRelinkInput,
  DocumentStructuredFieldPatch,
} from "./stores/documents";
export {
  createDocumentStore,
  discardRegisteredDocumentLocalState,
  getOrCreateDocumentStore,
  openDocumentStore,
  requestDomainDocumentSync,
  subscribeToPersistedDocuments,
} from "./stores/documents";
export type {
  EncryptedBlobStoreCipher,
  EncryptedBlobStoreKey,
  EncryptedBlobStoreOptions,
  WrapEncryptedBlobStoreOptions,
} from "./workflows/blobs";
export {
  createBlobStore,
  createEncryptedBlobStore,
  createLazyEncryptedBlobStore,
  createMemoryBlobStore,
  decryptDocumentAttachmentBlob,
  hydrateDocumentAttachmentBlobs,
  purgeOpfsBlobStore,
  uploadDocumentAttachment,
  wrapEncryptedBlobStore,
} from "./workflows/blobs";
export type {
  ContainerContentsRootAdopter,
  ContainerContentsRootAdoptionInput,
  ContainerContentsStoreWorkflowRuntime,
  ContainerContentsWorkflowRuntime,
  // Distinct from the canonical `ContainerDocumentLinkInput` (./client); the
  // documentQueries variant has a different shape, so it keeps a disambiguating
  // alias on the public surface.
  ContainerDocumentLinkInput as ContainerDocumentQueriesLinkInput,
  ContainerSystemSlotDefinition,
} from "./workflows/container-contents";
export {
  createContainerContentsDocumentsRuntime,
  createContainerContentsProjectionUserKeyResolver,
  createContainerContentsStoreWorkflowRuntime,
  createContainerContentsSyncLane,
  createContainerContentsWorkflowRuntime,
  createContainerParentSyncLane,
  createInitializedContainerMetadataDocument,
  defaultContainerContentsPersistence,
  deriveContainerSystemSlot,
  initializeDocumentLinksSchema,
  listBlobInfo,
  listDocumentLinkedContainerIds,
  loadContainerInfo,
  loadContainerSyncWatermark,
  loadDocumentAttributionRanges,
  loadDocumentInfo,
  replaceDocumentLinks,
  saveContainerSyncWatermark,
  syncedContainerDocumentObjectSyncState,
} from "./workflows/container-contents";
export type {
  AggregatedContainerKekLog,
  ContainerMutationAuthor,
  KeyringRebuildResult,
} from "./workflows/containers";
export {
  buildRootContainerCreatePlan,
  createRemoteContainer,
  fetchContainerKekLog,
  HistoricalWrapUnavailableError,
  type HistoricalWrapUnavailableReason,
  moveRemoteContainer,
  rebuildKeyringEntriesFromLog,
  recoverKeyringEntryFromWraps,
  rekeyRemoteContainer,
  revokeRemoteContainer,
  rootContainerWriterProjectionFromCreatePlan,
  shareRemoteContainer,
  shareRemoteContainerWithGroup,
} from "./workflows/containers";
export type {
  DocumentRecord,
  DocumentsPersistence,
  DocumentsWorkflowRuntime,
  DocumentsWorkflowRuntimeInput,
  LocalAttachmentRecord,
  PendingAttachmentRecord,
  PendingUpdateInsert,
  PendingUpdateRecord,
} from "./workflows/documents";
export {
  buildMaterializedDocumentCreatePlan,
  createDocumentProjectionUserKeyResolver,
  createDocumentsWorkflowRuntime,
  createRemoteDocument,
  DOCUMENT_SYNC_TRACE_FRAGMENT,
  DOCUMENT_SYNC_TRACE_PATTERN,
  DOCUMENTS_APP_KIND,
  defaultDocumentsPersistence,
  deletePersistedDocument,
  persistedDocumentCreateStateFromResponse,
  unwrapContainerKekPath,
  unwrapDocumentContentKeyTarget,
} from "./workflows/documents";
// Nominal identity constructors are deliberately absent here. Integration
// tests that compose low-level runtimes use the testing package subpath.
export type {
  OrganizationGroupPolicyHistoryEntry,
  OrganizationPrincipalMemberChange,
  OrganizationPrincipalMemberChangeType,
  OrganizationPrincipalPolicyHistory,
  OrganizationPrincipalPolicyHistoryEntry,
  ReconcileOrganizationDataUsageInput,
} from "./workflows/organizations";
export {
  addOrganizationGroupUser,
  buildInitialGroupPolicyRequest,
  buildInitialMemberGroupPolicyRequest,
  buildOrganizationGroupPolicyHistory,
  buildOrganizationProfileDocumentPatch,
  buildRosterProfileDocumentPatch,
  createInitializedRosterProfileDocument,
  createOrganizationGroup,
  DEFAULT_PERSONAL_ORGANIZATION_PROFILE_NAME,
  deriveOrganizationMetadataContainerSystemSlot,
  deriveOrganizationRosterProfileContainerSystemSlot,
  getOrganizationProfileDocumentLocalId,
  getRosterProfileDocumentLocalId,
  importOrganizationUser,
  loadLocalOrganizationDataUsage,
  loadLocalOrganizationDirectoryAndGroups,
  loadOrganizationBilling,
  loadOrganizationBillingHistory,
  loadOrganizationBillingManagementUrl,
  ORGANIZATION_METADATA_CONTAINER_NAME,
  ORGANIZATION_PROFILE_DOCUMENT_KIND,
  ORGANIZATION_ROSTER_PROFILE_CONTAINER_NAME,
  ROSTER_PROFILE_DOCUMENT_KIND,
  readOrganizationProfileName,
  reconcileOrganizationDataUsage,
  reconcileOrganizationDirectoryAndGroups,
  removeOrganizationGroupUser,
  resolveOrganizationBillingView,
  revokeOrganizationContainerGrant,
  startOrganizationTrial,
  subscribeOrganizationReadModelInvalidation,
  updateOrganizationProfile,
  updateOrganizationRosterEntry,
} from "./workflows/organizations";
export type { CacheReferencedPrincipalPoliciesOptions } from "./workflows/principals";
export { cacheReferencedPrincipalPolicies } from "./workflows/principals";
export type {
  InitialRootMetadataBootstrap,
  ProvisionedSystemContainerSpec,
  RegisterIdentityInput,
  RegistrationApi,
} from "./workflows/registration";
export {
  bootstrapRootContainer,
  buildInitialOrganizationPolicyRequest,
  createInitialRootMetadataBootstrap,
  persistRegistrationBootstrap,
  registerIdentity,
} from "./workflows/registration";
export type {
  ClearRemoteSyncStateResult,
  DomainSyncCoordinator,
  DomainSyncSnapshot,
  SyncIdleOptions,
  SyncLane,
  SyncLaneConfig,
  SyncLaneLastAction,
  SyncLanePhase,
  SyncLaneSnapshot,
  SyncLaneStatus,
} from "./workflows/sync";
export {
  clearRemoteSyncState,
  getDomainSyncCoordinatorSnapshot,
  getOrCreateDomainSyncCoordinator,
  hasDomainSyncCoordinatorPendingWork,
  requestAllDomainSyncLanes,
  subscribeToDomainSyncCoordinator,
  waitForDomainSyncCoordinatorToSettle,
} from "./workflows/sync";
