import type { WindowType } from '@/contexts/WindowManagerContext';

export const WINDOW_PATHS: Partial<Record<string, WindowType>> = {
  '/notes': 'notes',
  '/console': 'console',
  '/settings': 'settings',
  '/files': 'files',
  '/help': 'help',
  '/email': 'email',
  '/contacts': 'contacts',
  '/photos': 'photos',
  '/camera': 'camera',
  '/documents': 'documents',
  '/videos': 'videos',
  '/keychain': 'keychain',
  '/wallet': 'wallet',
  '/sqlite': 'sqlite',
  '/debug': 'debug',
  '/debug/system-info': 'debug',
  '/debug/browser/opfs': 'opfs',
  '/debug/browser/cache-storage': 'cache-storage',
  '/debug/browser/local-storage': 'local-storage',
  '/ai': 'chat',
  '/analytics': 'analytics',
  '/audio': 'audio',
  '/models': 'models',
  '/admin': 'admin',
  '/admin/redis': 'admin-redis',
  '/admin/postgres': 'admin-postgres',
  '/admin/groups': 'admin-groups',
  '/admin/users': 'admin-users',
  '/admin/organizations': 'admin-organizations',
  '/sync': 'sync',
  '/vfs': 'vfs',
  '/classic': 'classic',
  '/backups': 'backup',
  '/mls-chat': 'mls-chat',
  '/search': 'search',
  '/calendar': 'calendar',
  '/businesses': 'businesses',
  '/vehicles': 'vehicles',
  '/health': 'health'
};
