import {
  Activity,
  AppWindow,
  Archive,
  BarChart2,
  Bot,
  Bug,
  Building2,
  CalendarDays,
  Camera,
  CarFront,
  CircleHelp,
  CreditCard,
  Database,
  FileIcon,
  FileText,
  Film,
  FolderTree,
  HardDrive,
  HeartPulse,
  ImageIcon,
  KeyRound,
  Lock,
  Mail,
  MessageSquare,
  Music,
  RefreshCw,
  Save,
  Search,
  Settings,
  Shield,
  StickyNote,
  Table2,
  Terminal,
  User,
  Users
} from 'lucide-react';
import type { WindowType } from '@/contexts/WindowManagerContext';

export const WINDOW_ICONS: Record<WindowType, React.ReactNode> = {
  notes: <StickyNote className="h-3 w-3" />,
  console: <Terminal className="h-3 w-3" />,
  settings: <Settings className="h-3 w-3" />,
  files: <FileIcon className="h-3 w-3" />,
  search: <Search className="h-3 w-3" />,
  calendar: <CalendarDays className="h-3 w-3" />,
  businesses: <Building2 className="h-3 w-3" />,
  vehicles: <CarFront className="h-3 w-3" />,
  health: <HeartPulse className="h-3 w-3" />,
  tables: <Table2 className="h-3 w-3" />,
  debug: <Bug className="h-3 w-3" />,
  help: <CircleHelp className="h-3 w-3" />,
  documents: <FileText className="h-3 w-3" />,
  email: <Mail className="h-3 w-3" />,
  contacts: <User className="h-3 w-3" />,
  photos: <ImageIcon className="h-3 w-3" />,
  camera: <Camera className="h-3 w-3" />,
  videos: <Film className="h-3 w-3" />,
  keychain: <KeyRound className="h-3 w-3" />,
  wallet: <CreditCard className="h-3 w-3" />,
  sqlite: <Database className="h-3 w-3" />,
  opfs: <HardDrive className="h-3 w-3" />,
  ai: <MessageSquare className="h-3 w-3" />,
  analytics: <BarChart2 className="h-3 w-3" />,
  audio: <Music className="h-3 w-3" />,
  models: <Bot className="h-3 w-3" />,
  admin: <Shield className="h-3 w-3" />,
  'admin-redis': <Database className="h-3 w-3" />,
  'admin-postgres': <Database className="h-3 w-3" />,
  'admin-groups': <Users className="h-3 w-3" />,
  'admin-users': <User className="h-3 w-3" />,
  'admin-organizations': <Building2 className="h-3 w-3" />,
  'cache-storage': <Archive className="h-3 w-3" />,
  'local-storage': <HardDrive className="h-3 w-3" />,
  sync: <RefreshCw className="h-3 w-3" />,
  vfs: <FolderTree className="h-3 w-3" />,
  classic: <AppWindow className="h-3 w-3" />,
  backup: <Save className="h-3 w-3" />,
  'mls-chat': <Lock className="h-3 w-3" />,
  'notification-center': <Activity className="h-3 w-3" />
};

export const WINDOW_LABELS: Record<WindowType, string> = {
  notes: 'Notes',
  console: 'Console',
  settings: 'Settings',
  files: 'Files',
  search: 'Search',
  calendar: 'Calendar',
  businesses: 'Businesses',
  vehicles: 'Vehicles',
  health: 'Health',
  tables: 'Tables',
  debug: 'Debug',
  help: 'Help',
  documents: 'Documents',
  email: 'Email',
  contacts: 'Contacts',
  photos: 'Photos',
  camera: 'Camera',
  videos: 'Videos',
  keychain: 'Keychain',
  wallet: 'Wallet',
  sqlite: 'SQLite',
  opfs: 'OPFS',
  ai: 'AI',
  analytics: 'Analytics',
  audio: 'Audio',
  models: 'Models',
  admin: 'Admin',
  'admin-redis': 'Redis',
  'admin-postgres': 'Postgres',
  'admin-groups': 'Groups',
  'admin-users': 'Users Admin',
  'admin-organizations': 'Organizations Admin',
  'cache-storage': 'Cache Storage',
  'local-storage': 'Local Storage',
  sync: 'Sync',
  vfs: 'VFS Explorer',
  classic: 'Classic',
  backup: 'Backups',
  'mls-chat': 'MLS Chat',
  'notification-center': 'Notifications'
};

export function getWindowIcon(type: string): React.ReactNode {
  return WINDOW_ICONS[type as WindowType] ?? <AppWindow className="h-3 w-3" />;
}

export function getWindowLabel(type: string, title?: string): string {
  return title ?? WINDOW_LABELS[type as WindowType] ?? type;
}
