AllCops:
  Exclude:
    - android/**/*
    - ios/**/*
    - node_modules/**/*
    - public/**/*
    - vendor/bundle/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Metrics/BlockLength:
  Exclude:
    - fastlane/Fastfile.android.rb
    - fastlane/Fastfile.store.rb

Naming/FileName:
  Exclude:
    - fastlane/Fastfile.android.rb
    - fastlane/Fastfile.store.rb
