AllCops:
  Exclude:
    - android/**/*
    - ios/**/*
    - node_modules/**/*
    - public/**/*
    - vendor/bundle/**/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3

Metrics/BlockLength:
  Exclude:
    - fastlane/lanes/android.rb
    - fastlane/lanes/ios.rb
