import { expect, test } from "bun:test";
import {
  createDocument,
  encodeVersionVector,
  exportAllUpdates,
  importUpdates,
} from "@tearleads/loro";
import { isDocumentUpdateDominatedByBaseline } from "./documentBaselineDominance";
import { selectServedSyncUpdates } from "./documentSyncBaselineRedirect";

/**
 * Replays the exported TLC behaviors of the BaselineDominance model through
 * the real dominance and redirect kernels. The fixture is a committed TLC
 * artifact (regenerated by `bun run generate:protocol-traces`, drift-checked
 * by `bun run check:protocol-traces`), so the model and the implementation
 * are tied by artifact rather than by parallel construction: a model mutation
 * that weakens `Dominated`, drops the older-epoch condition, or bypasses
 * raw-mode completeness changes the fixture and disagrees here with both the
 * implementation and the independent abstract oracle below.
 */

const EXPECTED_BEHAVIOR_COUNT = 2048;
const FIXTURE_URL = new URL(
  "../../../../formal/document-sync/BaselineDominanceTraces.json",
  import.meta.url,
);

interface ExportedUpdate {
  readonly epoch: number;
  readonly frontier: readonly [number, number];
}

interface ExportedBehavior {
  readonly coverage: readonly [number, number];
  readonly currentEpoch: number;
  readonly dominated: readonly [boolean, boolean];
  readonly hasBaseline: boolean;
  readonly historyMode: "normal" | "raw";
  readonly served: readonly [boolean, boolean];
  readonly updates: readonly [ExportedUpdate, ExportedUpdate];
}

interface TraceFixture {
  readonly behaviors: readonly ExportedBehavior[];
  readonly bounds: {
    readonly maxCounter: number;
    readonly maxEpoch: number;
    readonly peers: number;
    readonly updateCount: number;
  };
}

async function loadFixture(): Promise<TraceFixture> {
  const fixture: TraceFixture = JSON.parse(await Bun.file(FIXTURE_URL).text());
  expect(fixture.bounds).toEqual({
    maxCounter: 1,
    maxEpoch: 2,
    peers: 2,
    updateCount: 2,
  });
  expect(fixture.behaviors).toHaveLength(EXPECTED_BEHAVIOR_COUNT);
  return fixture;
}

// Real Loro version vectors for the model's abstract counter pairs: one
// deterministic writer per peer, one committed op per counter step.
async function buildEncodedVectors(): Promise<ReadonlyMap<string, string>> {
  const prefixes: Array<Array<Uint8Array | null>> = [];
  for (const seed of ["trace-replay-peer-a", "trace-replay-peer-b"]) {
    const document = await createDocument(seed);
    document.getText("text").insert(0, "1");
    document.commit();
    prefixes.push([null, exportAllUpdates(document)]);
  }

  const encoded = new Map<string, string>();
  for (const firstCounter of [0, 1]) {
    for (const secondCounter of [0, 1]) {
      const document = await createDocument(
        `trace-replay-${firstCounter}-${secondCounter}`,
      );
      const updates = [
        prefixes[0]?.[firstCounter],
        prefixes[1]?.[secondCounter],
      ].filter((update): update is Uint8Array => !!update);
      importUpdates(document, updates);
      encoded.set(
        `${firstCounter},${secondCounter}`,
        encodeVersionVector(document),
      );
    }
  }
  return encoded;
}

function encodedVector(
  vectors: ReadonlyMap<string, string>,
  counters: readonly [number, number],
): string {
  const encoded = vectors.get(`${counters[0]},${counters[1]}`);
  if (!encoded) {
    throw new Error(`missing encoded vector for counters ${counters}`);
  }
  return encoded;
}

// The independent semantic oracle: componentwise counter dominance, computed
// without the model's operators and without the implementation's decoding.
function abstractlyDominated(
  behavior: ExportedBehavior,
  update: ExportedUpdate,
): boolean {
  return (
    behavior.hasBaseline &&
    update.epoch < behavior.currentEpoch &&
    behavior.coverage.every(
      (counter, index) => counter >= (update.frontier[index] ?? 0),
    )
  );
}

test("every exported TLC behavior replays through the sync kernels", async () => {
  const fixture = await loadFixture();
  const vectors = await buildEncodedVectors();

  for (const behavior of fixture.behaviors) {
    const coverage = encodedVector(vectors, behavior.coverage);
    const entries = behavior.updates.map((update, index) => ({
      id: `update-${index + 1}`,
      update: {
        partialEndVersionVector: encodedVector(vectors, update.frontier),
      },
      writeHeader: { contentKeyEpoch: update.epoch },
    }));
    const expectedServedIds = entries
      .filter((_, index) => behavior.served[index])
      .map((entry) => entry.id);

    const served = selectServedSyncUpdates({
      baselineCoverage: behavior.hasBaseline ? coverage : null,
      currentContentKeyEpoch: behavior.currentEpoch,
      entries,
      historyMode: behavior.historyMode === "raw" ? "raw" : undefined,
    });
    expect(served.map((entry) => entry.id)).toEqual(expectedServedIds);

    behavior.updates.forEach((update, index) => {
      expect(abstractlyDominated(behavior, update)).toBe(
        behavior.dominated[index] ?? false,
      );
      if (behavior.hasBaseline) {
        expect(
          isDocumentUpdateDominatedByBaseline({
            baselineEpoch: behavior.currentEpoch,
            baselineVersionVector: coverage,
            updateEpoch: update.epoch,
            updateVersionVector: encodedVector(vectors, update.frontier),
          }),
        ).toBe(behavior.dominated[index] ?? false);
      }
    });
  }
});
