import { Router, type Router as RouterType } from 'express';
import { registerDeleteGroupsGroupidRoute } from './deleteGroupsGroupId.js';
import { registerDeleteGroupsGroupidMembersUseridRoute } from './deleteGroupsGroupIdMembersUserId.js';
import { registerDeleteKeyPackagesIdRoute } from './deleteKeyPackagesId.js';
import { registerGetGroupsRoute } from './getGroups.js';
import { registerGetGroupsGroupidRoute } from './getGroupsGroupId.js';
import { registerGetGroupsGroupidMembersRoute } from './getGroupsGroupIdMembers.js';
import { registerGetGroupsGroupidStateRoute } from './getGroupsGroupIdState.js';
import { registerGetKeyPackagesMeRoute } from './getKeyPackagesMe.js';
import { registerGetKeyPackagesUseridRoute } from './getKeyPackagesUserId.js';
import { registerGetWelcomeMessagesRoute } from './getWelcomeMessages.js';
import { registerPatchGroupsGroupidRoute } from './patchGroupsGroupId.js';
import { registerPostGroupsRoute } from './postGroups.js';
import { registerPostGroupsGroupidMembersRoute } from './postGroupsGroupIdMembers.js';
import { registerPostGroupsGroupidStateRoute } from './postGroupsGroupIdState.js';
import { registerPostKeyPackagesRoute } from './postKeyPackages.js';
import { registerPostWelcomeMessagesIdAckRoute } from './postWelcomeMessagesIdAck.js';

const router: RouterType = Router();
registerPostKeyPackagesRoute(router);
registerGetKeyPackagesMeRoute(router);
registerGetKeyPackagesUseridRoute(router);
registerDeleteKeyPackagesIdRoute(router);
registerPostGroupsRoute(router);
registerGetGroupsRoute(router);
registerGetGroupsGroupidRoute(router);
registerPatchGroupsGroupidRoute(router);
registerDeleteGroupsGroupidRoute(router);
registerPostGroupsGroupidMembersRoute(router);
registerGetGroupsGroupidMembersRoute(router);
registerDeleteGroupsGroupidMembersUseridRoute(router);
registerGetWelcomeMessagesRoute(router);
registerPostWelcomeMessagesIdAckRoute(router);
registerPostGroupsGroupidStateRoute(router);
registerGetGroupsGroupidStateRoute(router);

export { router as mlsRouter };
