import { readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const DEFAULT_DIST_URL = new URL("../dist/", import.meta.url);

// Extensions worth precaching for an offline-capable shell. Source maps are
// deliberately excluded (debug-only, large), as is sw.js itself.
const PRECACHE_EXTENSIONS = new Set([
  ".css",
  ".html",
  ".ico",
  ".js",
  ".json",
  ".png",
  ".svg",
  ".wasm",
  ".woff",
  ".woff2",
]);
const REQUIRED_PRECACHE_URLS = ["/worker.js", "/sqlite3.wasm"] as const;
const CACHE_PREFIX = "symcrypt-app-web-";

export interface BuildServiceWorkerResult {
  cacheName: string;
  precacheUrls: string[];
  serviceWorkerSource: string;
}

function fileExtension(name: string): string {
  const dotIndex = name.lastIndexOf(".");
  return dotIndex === -1 ? "" : name.slice(dotIndex);
}

function normalizeDistUrl(distUrl: URL): URL {
  return distUrl.pathname.endsWith("/")
    ? distUrl
    : new URL(`${distUrl.pathname}/`, distUrl);
}

export async function listPrecacheFiles(
  distUrl: URL = DEFAULT_DIST_URL,
): Promise<string[]> {
  const normalizedDistUrl = normalizeDistUrl(distUrl);
  const distDir = fileURLToPath(normalizedDistUrl);
  // String-mode recursive readdir returns dist-relative paths for files and
  // directories; the extension filter below keeps only the asset files.
  const relativePaths = await readdir(distDir, { recursive: true });

  return relativePaths
    .map((relative) => `/${relative.replaceAll("\\", "/")}`)
    .filter((urlPath) => {
      if (urlPath.endsWith(".map") || urlPath === "/sw.js") {
        return false;
      }
      return PRECACHE_EXTENSIONS.has(fileExtension(urlPath));
    })
    .sort();
}

export async function computeCacheVersion(
  urlPaths: readonly string[],
  distUrl: URL = DEFAULT_DIST_URL,
): Promise<string> {
  const normalizedDistUrl = normalizeDistUrl(distUrl);
  // Hash the contents of every precached file so any change — including the
  // fixed-name /worker.js and /sqlite3.wasm — produces a new cache name (and a
  // byte-different sw.js, which is how the browser detects an update).
  const fileHashes = await Promise.all(
    urlPaths.map(async (urlPath) => {
      const bytes = await Bun.file(
        new URL(`.${urlPath}`, normalizedDistUrl),
      ).bytes();
      return `${urlPath}:${Bun.hash(bytes)}`;
    }),
  );
  return Bun.hash(fileHashes.join("\n")).toString(16);
}

function assertRequiredPrecacheUrls(precacheUrls: readonly string[]) {
  const missingUrls = REQUIRED_PRECACHE_URLS.filter(
    (urlPath) => !precacheUrls.includes(urlPath),
  );
  if (missingUrls.length > 0) {
    throw new Error(
      `Service worker precache is missing ${missingUrls.join(
        " and ",
      )} - run buildStaticAssets first.`,
    );
  }
}

function createServiceWorkerSource(params: {
  cacheName: string;
  precacheUrls: readonly string[];
}): string {
  return `// Auto-generated by scripts/buildServiceWorker.ts - do not edit by hand.
const CACHE_NAME = ${JSON.stringify(params.cacheName)};
const CACHE_PREFIX = ${JSON.stringify(CACHE_PREFIX)};
const PRECACHE_URLS = ${JSON.stringify(params.precacheUrls)};
const APP_SHELL_URL = "/index.html";

self.addEventListener("install", (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") {
    return;
  }

  const url = new URL(request.url);
  // Leave cross-origin traffic (the API and WebSocket) to the network.
  if (url.origin !== self.location.origin) {
    return;
  }

  // SPA navigations: prefer the network so deploys are picked up immediately,
  // and fall back to the cached shell when offline.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match(APP_SHELL_URL).then((cached) => cached ?? Response.error()),
      ),
    );
    return;
  }

  // Static assets (incl. /worker.js and /sqlite3.wasm): serve from cache, fall
  // back to the network for anything not precached.
  event.respondWith(
    caches.match(request).then((cached) => cached ?? fetch(request)),
  );
});
`;
}

// Generates dist/sw.js after the shell bundle and buildStaticAssets have placed
// every offline-critical file in dist.
export async function buildServiceWorker(
  distUrl: URL = DEFAULT_DIST_URL,
): Promise<BuildServiceWorkerResult> {
  const normalizedDistUrl = normalizeDistUrl(distUrl);
  const precacheUrls = await listPrecacheFiles(normalizedDistUrl);
  assertRequiredPrecacheUrls(precacheUrls);

  const cacheVersion = await computeCacheVersion(
    precacheUrls,
    normalizedDistUrl,
  );
  const cacheName = `${CACHE_PREFIX}${cacheVersion}`;
  const serviceWorkerSource = createServiceWorkerSource({
    cacheName,
    precacheUrls,
  });

  await Bun.write(new URL("sw.js", normalizedDistUrl), serviceWorkerSource);

  console.log(
    `Generated dist/sw.js (${cacheName}) precaching ${precacheUrls.length} assets.`,
  );

  return { cacheName, precacheUrls, serviceWorkerSource };
}

if (import.meta.main) {
  await buildServiceWorker();
}
