import { readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";

// Generates dist/sw.js: a small, self-contained precache service worker so the
// app shell + the SQLite worker + sqlite3.wasm are all available offline. This
// is what makes Explorer (and the rest of the device-first app) boot with no
// network — nginx serves /worker.js, /sqlite3.wasm and /index.html as
// `no-cache` (so they stay fresh across deploys), which means the HTTP cache
// alone cannot satisfy them offline. The service worker caches them in the Cache
// API instead, independent of those headers.
//
// Runs last in the build (after the shell bundle and buildStaticAssets), so the
// dist directory already contains every asset to precache.

const distUrl = new URL("../dist/", import.meta.url);
const distDir = fileURLToPath(distUrl);

// Extensions worth precaching for an offline-capable shell. Source maps are
// deliberately excluded (debug-only, large), as is sw.js itself.
const PRECACHE_EXTENSIONS = new Set([
  ".css",
  ".html",
  ".ico",
  ".js",
  ".json",
  ".png",
  ".svg",
  ".wasm",
  ".woff",
  ".woff2",
]);

function fileExtension(name: string): string {
  const dotIndex = name.lastIndexOf(".");
  return dotIndex === -1 ? "" : name.slice(dotIndex);
}

async function listPrecacheFiles(): Promise<string[]> {
  // String-mode recursive readdir returns dist-relative paths for files and
  // directories; the extension filter below keeps only the asset files.
  const relativePaths = await readdir(distDir, { recursive: true });

  return relativePaths
    .map((relative) => `/${relative.replaceAll("\\", "/")}`)
    .filter((urlPath) => {
      if (urlPath.endsWith(".map") || urlPath === "/sw.js") {
        return false;
      }
      return PRECACHE_EXTENSIONS.has(fileExtension(urlPath));
    })
    .sort();
}

async function computeCacheVersion(urlPaths: string[]): Promise<string> {
  // Hash the contents of every precached file so any change — including the
  // fixed-name /worker.js and /sqlite3.wasm — produces a new cache name (and a
  // byte-different sw.js, which is how the browser detects an update).
  const fileHashes = await Promise.all(
    urlPaths.map(async (urlPath) => {
      const bytes = await Bun.file(new URL(`.${urlPath}`, distUrl)).bytes();
      return `${urlPath}:${Bun.hash(bytes)}`;
    }),
  );
  return Bun.hash(fileHashes.join("\n")).toString(16);
}

const precacheUrls = await listPrecacheFiles();
if (
  !precacheUrls.includes("/worker.js") ||
  !precacheUrls.includes("/sqlite3.wasm")
) {
  throw new Error(
    "Service worker precache is missing /worker.js or /sqlite3.wasm — run buildStaticAssets first.",
  );
}

const cacheVersion = await computeCacheVersion(precacheUrls);
const cacheName = `tearleads-app-web-${cacheVersion}`;

// The service worker source. Conservative precache strategy:
// - install: cache the whole shell (+ worker + wasm).
// - activate: drop caches from previous versions.
// - fetch: navigations are network-first (always fresh online) with the cached
//   shell as the offline fallback; same-origin static assets are cache-first;
//   cross-origin requests (the API/WebSocket) are never intercepted.
// No skipWaiting/clients.claim, so a new version takes over on the next load
// rather than mid-session.
const serviceWorkerSource = `// Auto-generated by scripts/buildServiceWorker.ts — do not edit by hand.
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = ${JSON.stringify(precacheUrls)};
const APP_SHELL_URL = "/index.html";

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME)
            .map((key) => caches.delete(key)),
        ),
      ),
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") {
    return;
  }

  const url = new URL(request.url);
  // Leave cross-origin traffic (the API and WebSocket) to the network.
  if (url.origin !== self.location.origin) {
    return;
  }

  // SPA navigations: prefer the network so deploys are picked up immediately,
  // and fall back to the cached shell when offline.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match(APP_SHELL_URL).then((cached) => cached ?? Response.error()),
      ),
    );
    return;
  }

  // Static assets (incl. /worker.js and /sqlite3.wasm): serve from cache, fall
  // back to the network for anything not precached.
  event.respondWith(
    caches.match(request).then((cached) => cached ?? fetch(request)),
  );
});
`;

await Bun.write(new URL("sw.js", distUrl), serviceWorkerSource);

console.log(
  `Generated dist/sw.js (${cacheName}) precaching ${precacheUrls.length} assets.`,
);
