[package]
name = "http-client"
version = "0.1.0"
edition = "2024"

[dependencies]
protocol = { path = "../protocol" }
store = { path = "../store" }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
http-server = { path = "../http-server" }
axum = "0.8"
