export const ORG_MANAGER_LABELS = {
  add: "Add",
  addUser: "Add user",
  authenticate: "Authenticate to manage an organization.",
  access: "Access",
  accessAdmin: "Admin",
  accessRead: "Read",
  accessWrite: "Write",
  container: "Container",
  create: "Create",
  directory: "Directory",
  directoryUnavailable: "Directory unavailable.",
  directContainerLinks: "Direct container links",
  failedLoadDirectoryGroups: "Failed to load organization directory or groups.",
  failedLoadGrants: "Failed to load organization grants.",
  failedLoadGroupContainers: "Failed to load group container links.",
  failedLoadGroupMembers: "Failed to load group members.",
  failedLoadUserDetail: "Failed to load user detail.",
  grants: "Grants",
  grantsUnavailable: "Grants unavailable.",
  groupContainerLinks: "Group container links",
  groupName: "Group name",
  groups: "Groups",
  joined: "Joined",
  loadingDirectory: "Loading directory...",
  loadingGrants: "Loading grants...",
  loadingUserDetail: "Loading user detail...",
  members: "Members",
  noDirectUsers: "No direct users.",
  noDirectContainerLinks: "No direct container links.",
  noGroupContainerLinks: "No group container links.",
  noGroupMembers: "No group members.",
  noGroups: "No groups.",
  noOrganizationContainerLinks: "No organization-level container links.",
  noUserContainerLinks: "No direct user container links.",
  noPolicy: "No policy",
  organization: "Organization",
  organizationContainerLinks: "Organization-level container links",
  principal: "Principal",
  refresh: "Refresh",
  remove: "Remove",
  role: "Role",
  selectGroup: "Select a group.",
  selectUser: "Select a user.",
  self: "You",
  signingKey: "Signing key",
  uninitialized: "Uninitialized",
  updated: "Updated",
  user: "User",
  userContainerLinks: "Direct user container links",
  userDetailUnavailable: "User detail unavailable.",
  userId: "User ID",
  userNotFound: "User not found.",
} as const;

export function getOrgManagerEpochLabel(keyEpoch: number): string {
  return `Epoch ${keyEpoch}`;
}

export function getOrgManagerMemberCountLabel(memberCount: number): string {
  return `${memberCount} member${memberCount === 1 ? "" : "s"}`;
}
