// Re-export schema from @rapid/db
export {
  analyticsEvents,
  contactEmails,
  contactPhones,
  contacts,
  files,
  groups,
  migrations,
  notes,
  organizations,
  schema,
  secrets,
  syncMetadata,
  userCredentials,
  userGroups,
  userKeys,
  userOrganizations,
  userSettings,
  users,
  vfsAccess,
  vfsFolders,
  vfsLinks,
  vfsRegistry
} from '@rapid/db/sqlite';
