import type { AppConfig } from '../types.js';

/**
 * Generate strings.xml content for Android.
 * This sets the app display name.
 */
export function generateStringsXml(config: AppConfig): string {
  const urlScheme =
    config.urlScheme || config.bundleIds.android.split('.').reverse()[0];

  return `<?xml version='1.0' encoding='utf-8'?>
<!-- Generated by @tearleads/app-builder -->
<!-- App: ${config.displayName} (${config.id}) -->
<resources>
    <string name="app_name">${config.displayName}</string>
    <string name="title_activity_main">${config.displayName}</string>
    <string name="package_name">${config.bundleIds.android}</string>
    <string name="custom_url_scheme">${urlScheme}</string>
</resources>
`;
}

/**
 * Generate a Gradle script that can be applied to set app-specific configuration.
 * Usage in build.gradle: apply from: '../generated/app-config.gradle'
 */
export function generateAppConfigGradle(config: AppConfig): string {
  const urlScheme =
    config.urlScheme || config.bundleIds.android.split('.').reverse()[0];

  return `// Generated by @tearleads/app-builder
// App: ${config.displayName} (${config.id})
// Apply in build.gradle: apply from: '../generated/app-config.gradle'

ext {
    appId = "${config.id}"
    appDisplayName = "${config.displayName}"
    appBundleId = "${config.bundleIds.android}"
    appUrlScheme = "${urlScheme}"
}
`;
}
