import type { AppConfig } from '../types.js';

/**
 * Generate xcconfig content for iOS builds.
 * This can be used to inject app-specific build settings.
 */
export function generateXcconfig(config: AppConfig): string {
  const keychainPrefix = config.keychainPrefix || config.bundleIds.ios;

  return `// Generated by @tearleads/app-builder
// App: ${config.displayName} (${config.id})
// Do not edit manually - regenerate with: pnpm --filter @tearleads/app-builder generate --app ${config.id}

PRODUCT_BUNDLE_IDENTIFIER = ${config.bundleIds.ios}
PRODUCT_NAME = ${config.displayName}
KEYCHAIN_PREFIX = ${keychainPrefix}
URL_SCHEME = ${config.urlScheme || config.bundleIds.ios.split('.').reverse()[0]}
`;
}

/**
 * Generate Appfile content for Fastlane.
 */
export function generateAppfile(config: AppConfig): string {
  return `# Generated by @tearleads/app-builder
# App: ${config.displayName} (${config.id})

# Android
json_key_file(ENV['GOOGLE_PLAY_JSON_KEY_FILE'])
package_name('${config.bundleIds.android}')

# iOS
app_identifier('${config.bundleIds.ios}')
apple_id(ENV['APPLE_ID'])
itc_team_id(ENV['ITC_TEAM_ID'])
team_id(ENV['TEAM_ID'])
`;
}

/**
 * Generate Matchfile content for Fastlane Match.
 */
export function generateMatchfile(config: AppConfig): string {
  return `# Generated by @tearleads/app-builder
# App: ${config.displayName} (${config.id})

git_url(ENV['MATCH_GIT_URL'])
storage_mode('git')
app_identifier('${config.bundleIds.ios}')
username(ENV['APPLE_ID'])
team_id(ENV['TEAM_ID'])
`;
}

/**
 * Generate environment export script for CI.
 * This can be sourced in shell to set up the build environment.
 */
export function generateEnvScript(config: AppConfig): string {
  return `#!/bin/bash
# Generated by @tearleads/app-builder
# App: ${config.displayName} (${config.id})
# Source this file to set up the build environment: source env.sh

export APP_ID="${config.id}"
export APP_DISPLAY_NAME="${config.displayName}"
export APP_BUNDLE_ID_IOS="${config.bundleIds.ios}"
export APP_BUNDLE_ID_ANDROID="${config.bundleIds.android}"
export APP_BUNDLE_ID_DESKTOP="${config.bundleIds.desktop}"
`;
}
