import type { AppConfig } from '../types.js';

/**
 * Generate app-theme.css content from an app configuration.
 * This file defines CSS variables that override the default theme.
 */
export function generateAppThemeCss(config: AppConfig): string {
  const { theme } = config;

  return `/* Generated by @tearleads/app-builder */
/* App: ${config.displayName} (${config.id}) */
/* Do not edit manually - regenerate with: pnpm --filter @tearleads/app-builder generate --app ${config.id} */

:root {
  --primary: ${theme.primaryColor};
  --background: ${theme.backgroundColor};
  --accent: ${theme.accentColor};

  /* Derived variables */
  --ring: ${theme.primaryColor};
  --scrollbar-thumb-hover: ${theme.primaryColor};
}

/* Dark mode overrides if needed, or specific theme classes */
.dark {
  --primary: ${theme.primaryColor};
  /* We keep background dark usually, but can be customized */
}
`;
}
