export const CONTACTS_LABELS = {
  backToContactsAction: "Back to Contacts",
  contactUserIdField: "Contact user ID",
  copyUserIdAction: "Copy user ID",
  createContactAction: "Create",
  doneAction: "Done",
  editAction: "Edit",
  emptyState: "No contacts imported yet.",
  firstNameField: "First name",
  importContactAction: "Import Contact",
  importContactSubmitAction: "Import",
  lastNameField: "Last name",
  loadingState: "Loading contacts...",
  newContactAction: "New Contact",
  nicknameField: "Nickname",
  removeContactAction: "Move to Trash",
  selectState: "Select a contact.",
  unauthenticatedImportState: "Authenticate before importing peer keys.",
  userIdField: "Tearleads user ID",
  userIdPlaceholder: "User ID",
} as const;
