import type { NegativeControl } from "./protocolNegativeControls";

export const ATTACHMENT_NEGATIVE_CONTROLS: readonly NegativeControl[] = [
  {
    id: "hydration-overwrites-newer-document-intent",
    module: "formal/document-sync/AttachmentContentIdentity.tla",
    config: "formal/document-sync/AttachmentContentIdentity.cfg",
    constants: { CheckStoredIntent: "FALSE" },
    expect: { kind: "action", name: "HeldCopyNeverRegresses" },
    why: "Reloading a winning slot must not allow an older document view to overwrite the winner on its next hydration attempt.",
  },
  {
    id: "unlink-requires-unavailable-ciphertext",
    module: "formal/document-sync/AttachmentKeyReachability.tla",
    config: "formal/document-sync/AttachmentKeyReachability.cfg",
    constants: { RetainedTargetsNeedCiphertext: "TRUE" },
    expect: { kind: "liveness", name: "LinkedDocumentCanUnlink" },
    why: "Removing a retained target must remain possible when attachment ciphertext is unavailable.",
  },
  {
    id: "hydration-keeps-refused-copy",
    module: "formal/document-sync/AttachmentContentIdentity.tla",
    config: "formal/document-sync/AttachmentContentIdentity.cfg",
    constants: { RefreshRefusedCopy: "FALSE" },
    expect: { kind: "action", name: "RefusedCopyReloaded" },
    why: "After a competing facade wins, a refused hydration must reload its durable slot before the next attempt.",
  },
  {
    id: "link-rejects-retained-wrap",
    module: "formal/document-sync/AttachmentKeyReachability.tla",
    config: "formal/document-sync/AttachmentKeyReachability.cfg",
    constants: { ReuseRetiredWraps: "FALSE" },
    expect: { kind: "invariant", name: "ReenteredTargetsRemainWritable" },
    why: "Returning to a retired destination must reuse its retained envelope instead of conflicting with a freshly randomized wrap.",
  },
  {
    id: "link-misses-concurrent-attachment",
    module: "formal/document-sync/AttachmentKeyReachability.tla",
    config: "formal/document-sync/AttachmentKeyReachability.cfg",
    constants: { CheckBindingFrontier: "FALSE" },
    expect: { kind: "invariant", name: "CurrentReadersCanOpen" },
    why: "A concurrent binding must be covered before a new destination becomes visible.",
  },
  {
    id: "link-drops-prior-blob-wraps",
    module: "formal/document-sync/AttachmentKeyReachability.tla",
    config: "formal/document-sync/AttachmentKeyReachability.cfg",
    constants: { RetainPriorWraps: "FALSE" },
    expect: { kind: "invariant", name: "PriorWrapsRetained" },
    why: "Rewrapping and unlinking must retain earlier encrypted key packages.",
  },
  {
    id: "blob-requires-current-wrap",
    module: "formal/document-sync/AttachmentKeyReachability.tla",
    config: "formal/document-sync/AttachmentKeyReachability.cfg",
    constants: { UseHistoricalKeys: "FALSE" },
    expect: { kind: "invariant", name: "CurrentReadersCanOpen" },
    why: "A container rotation must remain readable through its verified historical keyring.",
  },
  {
    id: "attachment-failure-poisons-peers",
    module: "formal/document-sync/AttachmentKeyReachability.tla",
    config: "formal/document-sync/AttachmentKeyReachability.cfg",
    constants: { IsolateHydration: "FALSE" },
    expect: { kind: "invariant", name: "IndependentHydrationProgress" },
    why: "One unavailable attachment must not discard independent hydration successes.",
  },
  {
    id: "attachment-accepts-old-content",
    module: "formal/document-sync/AttachmentContentIdentity.tla",
    config: "formal/document-sync/AttachmentContentIdentity.cfg",
    constants: { CheckContentDigest: "FALSE" },
    expect: { kind: "invariant", name: "InstalledBytesMatchIntent" },
    why: "A valid historical binding can supply bytes different from the current signed document intent.",
  },
  {
    id: "attachment-commits-stale-intent",
    module: "formal/document-sync/AttachmentContentIdentity.tla",
    config: "formal/document-sync/AttachmentContentIdentity.cfg",
    constants: { CheckLiveIntent: "FALSE" },
    expect: { kind: "invariant", name: "InstalledBytesMatchIntent" },
    why: "The document can replace its attachment while hydration is in flight.",
  },
  {
    id: "attachment-overwrites-competing-copy",
    module: "formal/document-sync/AttachmentContentIdentity.tla",
    config: "formal/document-sync/AttachmentContentIdentity.cfg",
    constants: { CompareStoredCopy: "FALSE" },
    expect: { kind: "action", name: "StaleCopyCannotReplaceWinner" },
    why: "Another facade can install newer bytes while an older view is still hydrating.",
  },
  {
    id: "blob-bind-without-source-authority",
    module: "formal/blob-attachments/BlobSourceAuthority.tla",
    config: "formal/blob-attachments/BlobSourceAuthority.cfg",
    constants: { CheckSourceAuthority: "FALSE" },
    expect: { kind: "invariant", name: "BoundBytesHaveSourceAuthority" },
    why: "Destination write authority alone cannot authorize reuse of a private existing blob (#2266).",
  },
];
