export const EXPLORER_LABELS = {
  backToContainerAction: "Back to Container",
  blobBrowserAction: "Blob Browser",
  blobBrowserBackAction: "Back to Explorer",
  blobBrowserBlobColumn: "Blob",
  blobBrowserByteLengthRow: "Size",
  blobBrowserCopiedState: "copied",
  blobBrowserDocumentColumn: "Document",
  blobBrowserDocumentCountOne: "document",
  blobBrowserDocumentCountOther: "documents",
  blobBrowserDocumentInfoAction: "Info",
  blobBrowserEmpty: "No blobs.",
  blobBrowserIdRow: "Blob ID",
  blobBrowserLoading: "Loading...",
  blobBrowserLocalBytesMissing: "Local bytes are unavailable.",
  blobBrowserMetadataHeading: "Blob Metadata",
  blobBrowserMimeTypeColumn: "MIME",
  blobBrowserMimeTypeRow: "MIME Type",
  blobBrowserNoPreview: "No inline preview for this blob.",
  blobBrowserNoSelection: "Select a blob.",
  blobBrowserOpenBlobAction: "Open",
  blobBrowserOpenDocumentAction: "Open",
  blobBrowserPreviewHeading: "Preview",
  blobBrowserReferenceColumn: "References",
  blobBrowserReferenceCountOne: "reference",
  blobBrowserReferenceCountOther: "references",
  blobBrowserReferencesHeading: "Document Links",
  blobBrowserSearchPlaceholder:
    "Search blobs, storage keys, documents, or slots",
  blobBrowserSizeColumn: "Size",
  blobBrowserSlotColumn: "Slot",
  blobBrowserStateColumn: "State",
  blobBrowserStorageKeyColumn: "Storage",
  blobBrowserStorageKeyRow: "Storage Key",
  blobBrowserTextTruncated: "Preview truncated.",
  blobBrowserTitle: "Blob Browser",
  blobBrowserUpdatedColumn: "Updated",
  blobBrowserUpdatedRow: "Updated",
  containerInfoChooseGroupError: "Choose a group.",
  containerInfoCreatedRow: "Created",
  containerInfoCursorColumn: "Cursor",
  containerInfoEntryCountOne: "entry",
  containerInfoEntryCountOther: "entries",
  containerInfoEventPrefix: "event",
  containerInfoGrantCountOne: "grant",
  containerInfoGrantCountOther: "grants",
  containerInfoGroupField: "Group",
  containerInfoIdRow: "ID",
  containerInfoLaneColumn: "Lane",
  containerInfoLoading: "Loading...",
  containerInfoLocalDetailsHeading: "Local Details",
  containerInfoManifestColumn: "Manifest",
  containerInfoManifestHistoryRow: "Manifest History",
  containerInfoNoGrants: "No grants.",
  containerInfoNoGroupsOption: "No groups",
  containerInfoNoLocalCursor: "No local cursor",
  containerInfoPathColumn: "Path",
  containerInfoPathHeading: "Container Path",
  containerInfoPathRow: "Path",
  containerInfoPermissionAdmin: "admin",
  containerInfoPermissionColumn: "Permission",
  containerInfoPermissionField: "Permission",
  containerInfoPermissionRead: "read",
  containerInfoPermissionWrite: "write",
  containerInfoPrincipalColumn: "Principal",
  containerInfoPrincipalCountOne: "principal",
  containerInfoPrincipalCountOther: "principals",
  containerInfoPrincipalGrantsHeading: "Principal Grants",
  containerInfoRecipientsColumn: "Recipients",
  containerInfoRecipientTargetCountOne: "target",
  containerInfoRecipientTargetCountOther: "targets",
  containerInfoReferencedPrincipalCountOne: "referenced principal",
  containerInfoReferencedPrincipalCountOther: "referenced principals",
  containerInfoSavedColumn: "Saved",
  containerInfoSecurityHeading: "Security",
  containerInfoSecurityKeyEpochRow: "Key Epoch",
  containerInfoSecurityManifestHashRow: "Current Manifest Hash",
  containerInfoSecurityParentKeyEpochRow: "Parent Key Epoch",
  containerInfoShareAction: "Share",
  containerInfoShareGenericFailure: "Failed to share container.",
  containerInfoShareGenericFailureLog: "Failed to share container:",
  containerInfoShareToGroupFailure: "Failed to share container with group.",
  containerInfoShareToGroupHeading: "Share To Group",
  containerInfoShareToPeerAction: "Share With Peer",
  containerInfoShareToPeerFailure: "Failed to share container with peer.",
  containerInfoShareToPeerFailureLog: "Failed to share container with peer:",
  containerInfoShareToPeerHeading: "Share To Peer",
  containerInfoSharingAction: "Sharing...",
  containerInfoSourceColumn: "Source",
  containerInfoSourceDirect: "Direct",
  containerInfoSubjectTypeGroup: "group",
  containerInfoSubjectTypeOrganization: "organization",
  containerInfoSubjectTypeUser: "user",
  containerInfoSyncCursorsHeading: "Sync Cursors",
  containerInfoTitle: "Container Info",
  containerInfoTypeColumn: "Type",
  containerInfoUpdatedRow: "Updated",
  containerInfoWrapCountOne: "wrap",
  containerInfoWrapCountOther: "wraps",
  dateCreatedColumn: "Date created",
  dateModifiedColumn: "Date modified",
  documentBackToContainerAction: "Back to Container",
  documentDeleteAction: "Delete",
  documentInfoAccessEpochRow: "Access Epoch",
  documentInfoAccessStateHashRow: "Access State Hash",
  documentInfoAttachmentBlobColumn: "Blob",
  documentInfoAttachmentCountOne: "attachment",
  documentInfoAttachmentCountOther: "attachments",
  documentInfoAttachmentKindColumn: "State",
  documentInfoAttachmentNameColumn: "Name",
  documentInfoAttachmentsHeading: "Attachments & Blobs",
  documentInfoAttachmentSizeColumn: "Size",
  documentInfoAttachmentSlotColumn: "Slot",
  documentInfoAttachmentStateLocal: "local",
  documentInfoAttachmentStatePending: "pending",
  documentInfoAttachmentStateRemote: "remote",
  documentInfoAttachmentTimeColumn: "Time",
  documentInfoAuthorizingContainersHeading: "Authorizing Containers",
  documentInfoBackAction: "Back to Document",
  documentInfoBooleanNo: "no",
  documentInfoBooleanYes: "yes",
  documentInfoBundleContentKey: "content key",
  documentInfoBundleDocumentKek: "document KEK",
  documentInfoBundleManifest: "manifest",
  documentInfoBundleStateRow: "Runtime Bundles",
  documentInfoContainerColumn: "Container",
  documentInfoContainerManifestCountOne: "container manifest",
  documentInfoContainerManifestCountOther: "container manifests",
  documentInfoContainerRow: "Container",
  documentInfoContentKeyEpochRow: "Content Key Epoch",
  documentInfoContentKeyHashRow: "Content Key Target Hash",
  documentInfoContentTargetCountOne: "content target",
  documentInfoContentTargetCountOther: "content targets",
  documentInfoCurrentManifestHashRow: "Current Manifest Hash",
  documentInfoDocumentIdRow: "Document ID",
  documentInfoDocumentKekTargetCountOne: "KEK target",
  documentInfoDocumentKekTargetCountOther: "KEK targets",
  documentInfoDocumentKeyHashRow: "Document Key Target Hash",
  documentInfoDocumentManifestCountOne: "document manifest",
  documentInfoDocumentManifestCountOther: "document manifests",
  documentInfoDocumentManifestHistoryRow: "Document Manifest History",
  documentInfoEpochPrefix: "epoch",
  documentInfoGetInfoAction: "Get Info",
  documentInfoIdRow: "Local ID",
  documentInfoKeyEpochCountOne: "key epoch",
  documentInfoKeyEpochCountOther: "key epochs",
  documentInfoLastCommitRow: "Last Commit LSN",
  documentInfoLinkedContainersRow: "Linked Containers",
  documentInfoLinkedManifestCountOne: "manifest",
  documentInfoLinkedManifestCountOther: "manifests",
  documentInfoLoading: "Loading...",
  documentInfoLocalDetailsHeading: "Local Details",
  documentInfoLocalManifestHashRow: "Local Manifest Hash",
  documentInfoNoAttachments: "No attachments or blob bindings.",
  documentInfoNoAuthorizingContainers: "No authorizing containers.",
  documentInfoNoRemoteInfo: "Remote document security info is unavailable.",
  documentInfoPathEntryCountOne: "path entry",
  documentInfoPathEntryCountOther: "path entries",
  documentInfoPendingChangesRow: "Pending Changes",
  documentInfoPreviousManifestHashRow: "Previous Manifest Hash",
  documentInfoRemoteSecurityHeading: "Remote Security",
  documentInfoTargetCountRow: "Target Counts",
  documentInfoTitle: "Document Info",
  documentInfoTypeRow: "Type",
  documentInfoUpdateCountOne: "update",
  documentInfoUpdateCountOther: "updates",
  documentInfoUpdatedRow: "Updated",
  documentLinkAction: "Link",
  documentMoveAction: "Move",
  fileDropHint: "Drop files to import documents.",
  fileImportFailedStatus: "Some files could not be imported.",
  fileImportGenericFailure: "Failed to import files.",
  fileImportStoreNotReady: "Document store was not ready.",
  folderType: "Folder",
  itemNameColumn: "Name",
  itemSyncColumn: "Sync",
  itemTableEmpty: "No items.",
  itemTypeColumn: "Type",
  linkedContainerActivatingAction: "Activating...",
  linkedContainerActiveBadge: "Active",
  linkedContainerDetachAction: "Detach",
  linkedContainerDetachingAction: "Detaching...",
  linkedContainerMakeActiveAction: "Make Active",
  linkedContainersHeading: "Linked Containers",
  newStructuredDocumentAction: "New Structured Document",
  newStructuredDocumentDocumentTypeHeading: "Document Type",
  newStructuredDocumentRouteLabel: "New structured document",
  syncStateBlobCountOne: "blob",
  syncStateBlobCountOther: "blobs",
  syncStateError: "Error",
  syncStateLocal: "Local",
  syncStateOffline: "Offline",
  syncStatePending: "Pending",
  syncStatePendingBlobCountOne: "pending blob",
  syncStatePendingBlobCountOther: "pending blobs",
  syncStatePendingUpdateCountOne: "pending update",
  syncStatePendingUpdateCountOther: "pending updates",
  syncStateSynced: "Synced",
  unknownDate: "Unknown",
} as const;
