export const EXPLORER_LABELS = {
  blobBrowserAction: "Blob Browser",
  blobBrowserBackAction: "Back to Explorer",
  blobBrowserBackToListAction: "Back to List",
  blobBrowserBlobColumn: "Blob",
  blobBrowserByteLengthRow: "Size",
  blobBrowserCopiedState: "copied",
  blobBrowserDocumentColumn: "Document",
  blobBrowserDocumentCountOne: "document",
  blobBrowserDocumentCountOther: "documents",
  blobBrowserDocumentInfoAction: "Info",
  blobBrowserDownloadAction: "Download",
  blobBrowserEmpty: "No blobs.",
  blobBrowserIdRow: "Blob ID",
  blobBrowserLoading: "Loading...",
  blobBrowserLocalBytesMissing: "Local bytes are unavailable.",
  blobBrowserMetadataHeading: "Blob Metadata",
  blobBrowserMimeTypeColumn: "MIME",
  blobBrowserMimeTypeRow: "MIME Type",
  blobBrowserNoPreview: "No inline preview for this blob.",
  blobBrowserNoSelection: "Select a blob.",
  blobBrowserOpenBlobAction: "Open",
  blobBrowserOpenDocumentAction: "Open",
  blobBrowserPreviewHeading: "Preview",
  blobBrowserReferenceColumn: "References",
  blobBrowserReferenceCountOne: "reference",
  blobBrowserReferenceCountOther: "references",
  blobBrowserReferencesHeading: "Document Links",
  blobBrowserSearchPlaceholder:
    "Search blobs, storage keys, documents, or slots",
  blobBrowserSizeColumn: "Size",
  blobBrowserSlotColumn: "Slot",
  blobBrowserStateColumn: "State",
  blobBrowserStorageKeyColumn: "Storage",
  blobBrowserStorageKeyRow: "Storage Key",
  blobBrowserSyncHeading: "Sync Status",
  blobBrowserSyncIdle: "No active sync work.",
  blobBrowserTextTruncated: "Preview truncated.",
  blobBrowserTitle: "Blob Browser",
  blobBrowserUpdatedColumn: "Updated",
  blobBrowserUpdatedRow: "Updated",
  blobPickCancelAction: "Cancel",
  blobPickSubtitlePrefix: "Choose an image blob for",
  blobPickTitle: "Choose Blob",
  columnsMenuButton: "Columns",
  columnsMenuStateOff: "Off",
  columnsMenuStateOn: "On",
  compactSectionsTabsLabel: "Explorer sections",
  containerIconAlbumOption: "Photo Album",
  containerIconField: "Folder icon",
  containerIconFolderOption: "Folder",
  containerIconHeading: "Icon",
  containerIconPlaylistOption: "Music Playlist",
  containerIconUpdateFailure: "Failed to update the folder icon.",
  containerInfoChooseGroupError: "Choose a group.",
  containerInfoCreatedRow: "Created",
  containerInfoCursorColumn: "Cursor",
  containerInfoEntryCountOne: "entry",
  containerInfoEntryCountOther: "entries",
  containerInfoEventPrefix: "event",
  containerInfoGeneralTab: "General",
  containerInfoGrantCountOne: "grant",
  containerInfoGrantCountOther: "grants",
  containerInfoGroupField: "Group",
  containerInfoIdRow: "ID",
  containerInfoLaneColumn: "Lane",
  containerInfoLoading: "Loading...",
  containerInfoLocalDetailsHeading: "Local Details",
  containerInfoManifestColumn: "Manifest",
  containerInfoManifestHistoryRow: "Manifest History",
  containerInfoNoGrants: "No grants.",
  containerInfoNoGroupsOption: "No groups",
  containerInfoNoLocalCursor: "No local cursor",
  containerInfoNoRemoteInfo: "Remote container info is unavailable.",
  containerInfoPathColumn: "Path",
  containerInfoPathHeading: "Container Path",
  containerInfoPathRow: "Path",
  containerInfoPermissionAdmin: "admin",
  containerInfoPermissionColumn: "Permission",
  containerInfoPermissionField: "Permission",
  containerInfoPermissionRead: "read",
  containerInfoPermissionWrite: "write",
  containerInfoPrincipalColumn: "Principal",
  containerInfoPrincipalCountOne: "principal",
  containerInfoPrincipalCountOther: "principals",
  containerInfoPrincipalGrantsHeading: "Principal Grants",
  containerInfoRecipientsColumn: "Recipients",
  containerInfoRecipientTargetCountOne: "target",
  containerInfoRecipientTargetCountOther: "targets",
  containerInfoReferencedPrincipalCountOne: "referenced principal",
  containerInfoReferencedPrincipalCountOther: "referenced principals",
  containerInfoSavedColumn: "Saved",
  containerInfoSecurityHeading: "Security",
  containerInfoSecurityKeyEpochRow: "Key Epoch",
  containerInfoSecurityManifestHashRow: "Current Manifest Hash",
  containerInfoSecurityParentKeyEpochRow: "Parent Key Epoch",
  containerInfoSecurityTab: "Security",
  containerInfoShareAction: "Share",
  containerInfoShareGenericFailure: "Failed to share container.",
  containerInfoShareGenericFailureLog: "Failed to share container:",
  containerInfoShareToGroupFailure: "Failed to share container with group.",
  containerInfoShareToGroupHeading: "Share To Group",
  containerInfoShareToPeerAction: "Share With Peer",
  containerInfoShareToPeerFailure: "Failed to share container with peer.",
  containerInfoShareToPeerFailureLog: "Failed to share container with peer:",
  containerInfoShareToPeerHeading: "Share To Peer",
  containerInfoSharingAction: "Sharing...",
  containerInfoSharingTab: "Sharing",
  containerInfoSourceColumn: "Source",
  containerInfoSourceDirect: "Direct",
  containerInfoSubjectTypeGroup: "group",
  containerInfoSubjectTypeOrganization: "organization",
  containerInfoSubjectTypeUser: "user",
  containerInfoSyncCursorsHeading: "Sync Cursors",
  containerInfoSyncTab: "Sync",
  containerInfoTabsLabel: "Container info sections",
  containerInfoTitle: "Container Info",
  containerInfoTypeColumn: "Type",
  containerInfoUpdatedRow: "Updated",
  containerInfoWrapCountOne: "wrap",
  containerInfoWrapCountOther: "wraps",
  containerMoveToTrashAction: "Move to Trash",
  createChildFolderAction: "Create Child Folder",
  databaseLoadError: "Couldn't open the local database.",
  dateCreatedColumn: "Date created",
  dateModifiedColumn: "Date modified",
  documentDeleteAction: "Move to Trash",
  documentDownloadAction: "Download",
  documentInfoAccessEpochRow: "Access Epoch",
  documentInfoAccessStateHashRow: "Access State Hash",
  documentInfoAttachmentBlobColumn: "Blob",
  documentInfoAttachmentCountOne: "attachment",
  documentInfoAttachmentCountOther: "attachments",
  documentInfoAttachmentKindColumn: "State",
  documentInfoAttachmentNameColumn: "Name",
  documentInfoAttachmentsHeading: "Attachments & Blobs",
  documentInfoAttachmentSizeColumn: "Size",
  documentInfoAttachmentSlotColumn: "Slot",
  documentInfoAttachmentStateLocal: "local",
  documentInfoAttachmentStateLocalRemote: "local + remote",
  documentInfoAttachmentStatePending: "pending",
  documentInfoAttachmentStateRemote: "remote",
  documentInfoAttachmentTimeColumn: "Time",
  documentInfoAuthorizingContainersHeading: "Authorizing Containers",
  documentInfoBackAction: "Back to Document",
  documentInfoBooleanNo: "no",
  documentInfoBooleanYes: "yes",
  documentInfoBundleContentKey: "content key",
  documentInfoBundleDocumentKek: "document KEK",
  documentInfoBundleManifest: "manifest",
  documentInfoBlameHeading: "Blame",
  documentInfoBlameUnattributedTitle:
    "Not yet attributed (local or unsynced edit)",
  documentInfoBundleStateRow: "Runtime Bundles",
  documentInfoCharacterBlameCharacterPlural: "characters",
  documentInfoCharacterBlameCharacterSingular: "character",
  documentInfoCharacterBlameHeading: "Character Blame",
  documentInfoCharacterBlameUnattributed: "Unattributed",
  documentInfoContainerColumn: "Container",
  documentInfoContainerManifestCountOne: "container manifest",
  documentInfoContainerManifestCountOther: "container manifests",
  documentInfoContainerRow: "Container",
  documentInfoContentKeyEpochRow: "Content Key Epoch",
  documentInfoContentKeyHashRow: "Content Key Target Hash",
  documentInfoContentTargetCountOne: "content target",
  documentInfoContentTargetCountOther: "content targets",
  documentInfoContributorEditPlural: "edits",
  documentInfoContributorEditSingular: "edit",
  documentInfoContributorReasserted: "(re-asserted)",
  documentInfoContributorsHeading: "Contributors",
  documentInfoEditRangesHeading: "Edit Ranges",
  documentInfoEditRangeWriterColumn: "Writer",
  documentInfoEditRangePeerColumn: "Peer",
  documentInfoEditRangeRangeColumn: "Range",
  documentInfoEditRangeOpsColumn: "Ops",
  documentInfoEditRangeUploadColumn: "Upload",
  documentInfoEditRangeAuthorityColumn: "Authority",
  documentInfoEditRangeAuthorityDirect: "Direct",
  documentInfoEditRangeAuthorityReasserted: "Re-asserted",
  documentInfoCurrentManifestHashRow: "Current Manifest Hash",
  documentInfoDocumentIdRow: "Document ID",
  documentInfoDocumentKekTargetCountOne: "KEK target",
  documentInfoDocumentKekTargetCountOther: "KEK targets",
  documentInfoDocumentKeyHashRow: "Document Key Target Hash",
  documentInfoDocumentManifestCountOne: "document manifest",
  documentInfoDocumentManifestCountOther: "document manifests",
  documentInfoDocumentManifestHistoryRow: "Document Manifest History",
  documentInfoEpochPrefix: "epoch",
  documentInfoFieldBlameHeading: "Field Blame",
  documentInfoGetInfoAction: "Get Info",
  documentInfoBlobsTab: "Blobs",
  documentInfoGeneralHeading: "General Details",
  documentInfoGeneralTab: "General",
  documentInfoIdRow: "Local ID",
  documentInfoKeyEpochCountOne: "key epoch",
  documentInfoKeyEpochCountOther: "key epochs",
  documentInfoLastCommitRow: "Last Commit LSN",
  documentInfoLinksTab: "Links",
  documentInfoLinkedContainersRow: "Linked Containers",
  documentInfoLinkedManifestCountOne: "manifest",
  documentInfoLinkedManifestCountOther: "manifests",
  documentInfoLoading: "Loading...",
  documentInfoLocalSecurityHeading: "Local Security",
  documentInfoLocalManifestHashRow: "Local Manifest Hash",
  documentInfoNoAttachments: "No attachments or blob bindings.",
  documentInfoNoAuthorizingContainers: "No authorizing containers.",
  documentInfoNoContributors: "No edit attribution available.",
  documentInfoNoRemoteInfo: "Remote document security info is unavailable.",
  documentInfoPathEntryCountOne: "path entry",
  documentInfoPathEntryCountOther: "path entries",
  documentInfoPendingChangesRow: "Pending Changes",
  documentInfoPreviousManifestHashRow: "Previous Manifest Hash",
  documentInfoRemoteSecurityHeading: "Remote Security",
  documentInfoSecurityTab: "Security",
  documentInfoTabsLabel: "Document info sections",
  documentInfoTargetCountRow: "Target Counts",
  documentInfoTitle: "Document Info",
  documentInfoTypeRow: "Type",
  documentInfoUpdateCountOne: "update",
  documentInfoUpdateCountOther: "updates",
  documentInfoUpdatedRow: "Updated",
  documentLinkAction: "Link",
  documentMoveAction: "Move",
  documentPurgeAction: "Delete Forever",
  fileDropHint: "Drop files to import documents.",
  fileImportBlockedByContainer: "This folder does not accept uploads.",
  fileImportFailedStatus: "Some files could not be imported.",
  fileImportGenericFailure: "Failed to import files.",
  fileImportStoreNotReady: "Document store was not ready.",
  folderType: "Folder",
  itemActionsButtonPrefix: "Actions for",
  itemActionsColumn: "Actions",
  itemNameColumn: "Name",
  itemSyncColumn: "Sync",
  itemTableEmpty: "No items.",
  uploadAction: "Upload",
  itemTypeColumn: "Type",
  linkedContainerActivatingAction: "Activating...",
  linkedContainerActiveBadge: "Active",
  linkedContainerDetachAction: "Detach",
  linkedContainerDetachingAction: "Detaching...",
  linkedContainerMakeActiveAction: "Make Active",
  linkedContainersEmpty: "No linked containers.",
  linkedContainersHeading: "Linked Containers",
  newContactAction: "New Contact",
  newStructuredDocumentAction: "New Document",
  newStructuredDocumentDocumentTypeHeading: "Document Type",
  newStructuredDocumentRouteLabel: "New document",
  retry: "Retry",
  sharedWithMeSection: "Shared with me",
  syncLanesAction: "Sync Lanes",
  syncLanesBackAction: "Back to Explorer",
  syncLanesBackToListAction: "Back to Sync Lanes",
  syncLanesBlobPhase: "Blob",
  syncLanesBooleanNo: "no",
  syncLanesBooleanYes: "yes",
  syncLanesBytesRow: "Bytes",
  syncLanesCompleteMetric: "Complete",
  syncLanesCoordinatorHeading: "Coordinator",
  syncLanesCompactBlobUpload: "Blob upload",
  syncLanesCompactContainerContents: "Container contents",
  syncLanesCompactDocument: "Document",
  syncLanesCompactReconciliation: "Reconciliation",
  syncLanesCountsColumn: "Counts",
  syncLanesSyncNowAction: "Sync now",
  syncLanesDetailTitle: "Sync Lane Detail",
  syncLanesDetailTabsLabel: "Sync lane detail sections",
  syncLanesDocumentPhase: "Document",
  syncLanesErrorMetric: "Errors",
  syncLanesErrorCountOne: "error",
  syncLanesErrorCountOther: "errors",
  syncLanesGeneralHeading: "Lane Details",
  syncLanesIdleMetric: "Idle",
  syncLanesKeyRow: "Key",
  syncLanesLabelRow: "Label",
  syncLanesLaneColumn: "Lane",
  syncLanesLaneNotFound: "Sync lane not found:",
  syncLanesLastActionColumn: "Last Action",
  syncLanesLastActionAtRow: "Last Action At",
  syncLanesLastActionCompleted: "Completed",
  syncLanesLastActionFailed: "Failed",
  syncLanesLastActionRegistered: "Registered",
  syncLanesLastActionRequested: "Requested",
  syncLanesLastActionStarted: "Started",
  syncLanesLastCompletedRow: "Last Completed",
  syncLanesLastErrorRow: "Last Error",
  syncLanesLastFailedRow: "Last Failed",
  syncLanesLastRequestedRow: "Last Requested",
  syncLanesLastStartedRow: "Last Started",
  syncLanesNoError: "No error",
  syncLanesNoLanes: "No sync lanes.",
  syncLanesOpenLaneAction: "Open lane detail",
  syncLanesPhaseColumn: "Phase",
  syncLanesPartsRow: "Parts",
  syncLanesPendingWorkRow: "Pending Work",
  syncLanesProgressHeading: "Upload Progress",
  syncLanesProgressColumn: "Progress",
  syncLanesProgressPercentRow: "Progress Percent",
  syncLanesPumpActiveRow: "Pump Active",
  syncLanesQueuedMetric: "Queued",
  syncLanesRegistrationRow: "Registration",
  syncLanesRegisteredMetric: "Registered",
  syncLanesRequestCountOne: "request",
  syncLanesRequestCountOther: "requests",
  syncLanesRequestedRow: "Requested",
  syncLanesRunCountOne: "run",
  syncLanesRunCountOther: "runs",
  syncLanesRunningRow: "Running",
  syncLanesRunningMetric: "Running",
  syncLanesSnapshotUpdatedRow: "Snapshot Updated",
  syncLanesStatusColumn: "Status",
  syncLanesStatusComplete: "Complete",
  syncLanesStatusError: "Error",
  syncLanesStatusIdle: "Idle",
  syncLanesStatusQueued: "Queued",
  syncLanesStatusRunning: "Running",
  syncLanesStructuralPhase: "Structural",
  syncLanesTimingHeading: "Timing",
  syncLanesTitle: "Sync Lanes",
  syncLanesUploadPartOne: "part",
  syncLanesUploadPartOther: "parts",
  syncSectionsAction: "Sync",
  syncStateBlobCountOne: "blob",
  syncStateBlobCountOther: "blobs",
  syncStateError: "Error",
  syncStateLocal: "Local",
  syncStateOffline: "Offline",
  syncStatePending: "Pending",
  syncStatePendingBlobCountOne: "pending blob",
  syncStatePendingBlobCountOther: "pending blobs",
  syncStatePendingUpdateCountOne: "pending update",
  syncStatePendingUpdateCountOther: "pending updates",
  syncStateSynced: "Synced",
  unknownDate: "Unknown",
} as const;
