import { Router, type Router as RouterType } from 'express';
import { registerDeleteGroupsGroupidRoute } from './mls/delete-groups-groupId.js';
import { registerDeleteGroupsGroupidMembersUseridRoute } from './mls/delete-groups-groupId-members-userId.js';
import { registerDeleteKeyPackagesIdRoute } from './mls/delete-key-packages-id.js';
import { registerGetGroupsRoute } from './mls/get-groups.js';
import { registerGetGroupsGroupidRoute } from './mls/get-groups-groupId.js';
import { registerGetGroupsGroupidMembersRoute } from './mls/get-groups-groupId-members.js';
import { registerGetGroupsGroupidMessagesRoute } from './mls/get-groups-groupId-messages.js';
import { registerGetGroupsGroupidStateRoute } from './mls/get-groups-groupId-state.js';
import { registerGetKeyPackagesMeRoute } from './mls/get-key-packages-me.js';
import { registerGetKeyPackagesUseridRoute } from './mls/get-key-packages-userId.js';
import { registerGetWelcomeMessagesRoute } from './mls/get-welcome-messages.js';
import { registerPatchGroupsGroupidRoute } from './mls/patch-groups-groupId.js';
import { registerPostGroupsRoute } from './mls/post-groups.js';
import { registerPostGroupsGroupidMembersRoute } from './mls/post-groups-groupId-members.js';
import { registerPostGroupsGroupidMessagesRoute } from './mls/post-groups-groupId-messages.js';
import { registerPostGroupsGroupidStateRoute } from './mls/post-groups-groupId-state.js';
import { registerPostKeyPackagesRoute } from './mls/post-key-packages.js';
import { registerPostWelcomeMessagesIdAckRoute } from './mls/post-welcome-messages-id-ack.js';

const router: RouterType = Router();
registerPostKeyPackagesRoute(router);
registerGetKeyPackagesMeRoute(router);
registerGetKeyPackagesUseridRoute(router);
registerDeleteKeyPackagesIdRoute(router);
registerPostGroupsRoute(router);
registerGetGroupsRoute(router);
registerGetGroupsGroupidRoute(router);
registerPatchGroupsGroupidRoute(router);
registerDeleteGroupsGroupidRoute(router);
registerPostGroupsGroupidMembersRoute(router);
registerGetGroupsGroupidMembersRoute(router);
registerDeleteGroupsGroupidMembersUseridRoute(router);
registerPostGroupsGroupidMessagesRoute(router);
registerGetGroupsGroupidMessagesRoute(router);
registerGetWelcomeMessagesRoute(router);
registerPostWelcomeMessagesIdAckRoute(router);
registerPostGroupsGroupidStateRoute(router);
registerGetGroupsGroupidStateRoute(router);

export { router as mlsRouter };
