import { Router, type Router as RouterType } from 'express';
import { registerDeleteGroupsGroupidRoute } from './mls/deleteGroupsGroupId.js';
import { registerDeleteGroupsGroupidMembersUseridRoute } from './mls/deleteGroupsGroupIdMembersUserId.js';
import { registerDeleteKeyPackagesIdRoute } from './mls/deleteKeyPackagesId.js';
import { registerGetGroupsRoute } from './mls/getGroups.js';
import { registerGetGroupsGroupidRoute } from './mls/getGroupsGroupId.js';
import { registerGetGroupsGroupidMembersRoute } from './mls/getGroupsGroupIdMembers.js';
import { registerGetGroupsGroupidMessagesRoute } from './mls/getGroupsGroupIdMessages.js';
import { registerGetGroupsGroupidStateRoute } from './mls/getGroupsGroupIdState.js';
import { registerGetKeyPackagesMeRoute } from './mls/getKeyPackagesMe.js';
import { registerGetKeyPackagesUseridRoute } from './mls/getKeyPackagesUserId.js';
import { registerGetWelcomeMessagesRoute } from './mls/getWelcomeMessages.js';
import { registerPatchGroupsGroupidRoute } from './mls/patchGroupsGroupId.js';
import { registerPostGroupsRoute } from './mls/postGroups.js';
import { registerPostGroupsGroupidMembersRoute } from './mls/postGroupsGroupIdMembers.js';
import { registerPostGroupsGroupidMessagesRoute } from './mls/postGroupsGroupIdMessages.js';
import { registerPostGroupsGroupidStateRoute } from './mls/postGroupsGroupIdState.js';
import { registerPostKeyPackagesRoute } from './mls/postKeyPackages.js';
import { registerPostWelcomeMessagesIdAckRoute } from './mls/postWelcomeMessagesIdAck.js';

const router: RouterType = Router();
registerPostKeyPackagesRoute(router);
registerGetKeyPackagesMeRoute(router);
registerGetKeyPackagesUseridRoute(router);
registerDeleteKeyPackagesIdRoute(router);
registerPostGroupsRoute(router);
registerGetGroupsRoute(router);
registerGetGroupsGroupidRoute(router);
registerPatchGroupsGroupidRoute(router);
registerDeleteGroupsGroupidRoute(router);
registerPostGroupsGroupidMembersRoute(router);
registerGetGroupsGroupidMembersRoute(router);
registerDeleteGroupsGroupidMembersUseridRoute(router);
registerPostGroupsGroupidMessagesRoute(router);
registerGetGroupsGroupidMessagesRoute(router);
registerGetWelcomeMessagesRoute(router);
registerPostWelcomeMessagesIdAckRoute(router);
registerPostGroupsGroupidStateRoute(router);
registerGetGroupsGroupidStateRoute(router);

export { router as mlsRouter };
