---
- name: Deploy blob GC systemd service
  ansible.builtin.template:
    src: etc/systemd/system/symcrypt-blob-gc.service.j2
    dest: /etc/systemd/system/symcrypt-blob-gc.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Deploy blob GC systemd timer
  ansible.builtin.template:
    src: etc/systemd/system/symcrypt-blob-gc.timer.j2
    dest: /etc/systemd/system/symcrypt-blob-gc.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Enable blob GC systemd timer
  ansible.builtin.systemd:
    name: symcrypt-blob-gc.timer
    daemon_reload: true
    enabled: true
    state: started

- name: Deploy Stripe seat sync systemd service
  ansible.builtin.template:
    src: etc/systemd/system/symcrypt-stripe-seat-sync.service.j2
    dest: /etc/systemd/system/symcrypt-stripe-seat-sync.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Deploy Stripe seat sync systemd timer
  ansible.builtin.template:
    src: etc/systemd/system/symcrypt-stripe-seat-sync.timer.j2
    dest: /etc/systemd/system/symcrypt-stripe-seat-sync.timer
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Enable Stripe seat sync systemd timer
  ansible.builtin.systemd:
    name: symcrypt-stripe-seat-sync.timer
    daemon_reload: true
    enabled: true
    state: started
