export const MAX_DOCUMENT_SYNC_REQUEST_BYTES = 16 * 1024 * 1024;

export const MAX_DOCUMENT_SYNC_OUTGOING_UPDATES = 64;
export const MAX_DOCUMENT_SYNC_UPDATE_DATA_CHARACTERS = 8 * 1024 * 1024;
export const MAX_DOCUMENT_SYNC_ENCRYPTED_DATA_CHARACTERS =
  MAX_DOCUMENT_SYNC_UPDATE_DATA_CHARACTERS + 4 * 1024;
export const MAX_DOCUMENT_SYNC_VERSION_VECTOR_CHARACTERS = 64 * 1024;

export const MAX_DOCUMENT_SYNC_AUTHORIZATION_PATHS = 64;
export const MAX_DOCUMENT_SYNC_AUTHORIZATION_PATH_DEPTH = 100;
export const MAX_DOCUMENT_SYNC_AUTHORIZATION_PATH_REFS = 256;
export const MAX_DOCUMENT_SYNC_CONTENT_KEY_TARGETS = 64;
